songs = [
    ('Strange Fruit', 1939, '3:10', 'Lady Day: The Best of Billie Holiday', 'Jazz', 'Billie Holiday'),
    ('God Bless the Child', 1941, '3:00', 'Lady Day: The Best of Billie Holiday', 'Jazz', 'Billie Holiday'),
    ('Lover Man (Oh, Where Can You Be?)', 1945, '3:16', 'The Quintessential Billie Holiday, Vol. 9: 1944-1945', 'Jazz', 'Billie Holiday'),
    ('Summertime', 1936, '2:55', 'The Quintessential Billie Holiday, Vol. 1: 1933-1935', 'Jazz', 'Billie Holiday'),
    ('Billie Jean', 1982, '4:54', 'Thriller', 'Pop', 'Michael Jackson'),
    ('Kiss the Rain', 1998, '4:09', 'Growing, Pains', 'Pop', 'Billie Myers'),
    ('The Petite Waltz (La Petite Valse)', 1951, '2:48', 'The Petite Waltz', 'Easy Listening', 'Billy Cotton & his Band'),
    ('My Foolish Heart', 1950, '3:11', 'My Foolish Heart', 'Jazz', 'Billy Eckstine'),
    ('I Apologize', 1951, '2:51', 'I Apologize', 'Jazz', 'Billy Eckstine'),
    ('Cradle of Love', 1990, '4:39', 'Charmed Life', 'Rock', 'Billy Idol'),
    ('Eyes Without a Face', 1984, '4:58', 'Rebel Yell', 'Rock', 'Billy Idol'),
    ('Mony Mony (Live)', 1987, '5:01', 'Vital Idol', 'Rock', 'Billy Idol'),
    ('White Wedding', 1983, '4:12', 'Billy Idol', 'Rock', 'Billy Idol'),
    ('Little Children', 1964, '2:47', 'Little Children', 'Pop', 'Billy J Kramer & The Dakotas'),
    ('The River of Dreams', 1993, '4:06', 'River of Dreams', 'Rock', 'Billy Joel'),
    ('Uptown Girl', 1983, '3:14', 'An Innocent Man', 'Pop', 'Billy Joel'),
    ('Just the Way You Are', 1978, '4:48', 'The Stranger', 'Pop', 'Billy Joel'),
    ('My Life', 1979, '4:43', '52nd Street', 'Pop', 'Billy Joel'),
    ("We Didn't Start the Fire", 1989, '4:49', 'Storm Front', 'Pop', 'Billy Joel'),
    ('Tell Her About It', 1983, '3:51', 'An Innocent Man', 'Pop', 'Billy Joel'),
    ("It's Still Rock 'n' Roll to Me", 1980, '2:57', 'Glass Houses', 'Pop', 'Billy Joel'),
    ('Piano Man', 1974, '5:37', 'Piano Man', 'Rock', 'Billy Joel'),
    ('Yes! We Have No Bananas', 1923, '3:06', 'Yes! We Have No Bananas', 'Pop', 'Billy Jones'),
    ('Get Outta My Dreams Get Into My Car', 1988, '4:46', 'Tear Down These Walls', 'Pop', 'Billy Ocean'),
    ('When the Going Gets Tough, the Tough Get Going', 1986, '4:08', 'Love Zone', 'Pop', 'Billy Ocean'),
    ('Caribbean Queen (No More Love On the Run)', 1984, '4:06', 'Suddenly', 'Pop', 'Billy Ocean'),
    ("There'll Be Sad Songs (To Make You Cry)", 1986, '4:49', 'Love Zone', 'Pop', 'Billy Ocean'),
    ('Loverboy', 1985, '4:10', 'Suddenly', 'Pop', 'Billy Ocean'),
    ('Love Really Hurts Without You', 1976, '3:00', 'Billy Ocean', 'Pop', 'Billy Ocean'),
    ('Me & Mrs Jones', 1973, '4:46', '360 Degrees of Billy Paul', 'Soul', 'Billy Paul'),
    ('Will It Go Round In Circles', 1973, '3:47', 'The Kids & Me', 'R&B', 'Billy Preston'),
    ('Nothing From Nothing', 1974, '2:35', 'The Kids & Me', 'R&B', 'Billy Preston'),
    ("With You I'm Born Again", 1980, '3:35', 'Late at Night', 'R&B', 'Billy Preston & Syreeta'),
    ('Achy Breaky Heart', 1992, '3:23', 'Some Gave All', 'Country', 'Billy Ray Cyrus'),
    ('I Can Help', 1975, '3:58', 'I Can Help', 'Country', 'Billy Swan'),
    ('Sail Along Silvery Moon', 1958, '2:09', 'Golden Instrumentals', 'Easy Listening', 'Billy Vaughn'),
    ('Melody of Love', 1955, '3:12', 'Melody of Love', 'Easy Listening', 'Billy Vaughn'),
    ('Wheels (Vier Schimmel, ein Wagen)', 1961, '1:58', 'Golden Instrumentals', 'Easy Listening', 'Billy Vaughn'),
    ('La Paloma', 1958, '2:08', 'Golden Instrumentals', 'Easy Listening', 'Billy Vaughn'),
    ('At This Moment', 1987, '4:17', 'By Request: The Best of Billy Vera & The Beaters', 'Pop', 'Billy Vera'),
    ('Sixty Minute Man', 1951, '2:34', 'The Chronological Billy Ward & The Dominoes 1951-1953', 'R&B', 'Billy Ward & The Dominoes'),
    ('Hop Scotch Polka', 1950, '2:34', 'The Chronological Billy Whitlock 1950-1952', 'Pop', 'Billy Whitlock'),
    ('El Bimbo', 1975, '2:32', 'El Bimbo', 'Disco', 'Bimbo Jet'),
    ('White Christmas', 1942, '3:03', 'Merry Christmas', 'Holiday', 'Bing Crosby'),
    ('Swinging On a Star', 1944, '2:32', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby'),
    ('Pennies From Heaven', 1936, '3:07', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby'),
    ("I'll be seeing you", 1944, '3:01', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby'),
    ('Sunday, Monday or Always', 1943, '3:09', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby'),
    ('Now Is the Hour (Maori Farewell Song)', 1948, '2:36', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby'),
    ('Only Forever', 1940, '3:10', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby'),
    ('Brother, Can You Spare a Dime?', 1932, '3:15', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby'),
    ('Sweet Leilani', 1937, '3:13', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby'),
    ('Too-Ra-Loo-Ra-Loo-Ra', 1944, '3:21', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby'),
    ('I Love You', 1944, '3:13', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby'),
    ('Moonlight Becomes You', 1942, '3:12', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby'),
    ('Rudolph, the Red-Nosed Reindeer', 1950, '2:10', 'Merry Christmas', 'Holiday', 'Bing Crosby'),
    ('Dolores', 1941, '2:57', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby'),
    ('Love in Bloom', 1934, '3:13', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby'),
    ('San Fernando Valley', 1944, '3:14', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby'),
    ('On the Atchison, Topeka & the Santa Fe', 1945, '3:06', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby'),
    ('June in January', 1934, '2:45', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby'),
    ('Silent Night, Holy Night', 1935, '2:54', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby'),
    ('Please', 1932, '3:14', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby'),
    ('Out of Nowhere', 1931, '3:20', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby'),
    ('You Are My Sunshine', 1941, '2:28', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby'),
    ('Trade Winds', 1940, '3:15', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby'),
    ('Red Sails in the Sunset', 1935, '3:13', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby'),
    ("I've Got a Pocketful of Dreams", 1938, '2:59', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby'),
    ('You Must Have Been a Beautiful Baby', 1938, '3:09', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby'),
    ('The Moon Got in My Eyes', 1937, '3:17', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby'),
    ("I Can't Begin to Tell You", 1945, '2:59', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby & Carmen Cavallaro'),
    ("Alexander's ragtime band", 1938, '3:00', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby & Connee Boswell'),
    ('True Love', 1956, '2:35', 'High Society', 'Soundtrack', 'Bing Crosby & Grace Kelly'),
    ("It's Been a Long, Long Time", 1945, '3:21', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby & Les Paul'),
    ("Don't Fence Me In", 1944, '3:06', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby & The Andrews Sisters'),
    ("Pistol Packin' Mama", 1943, '3:00', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby & The Andrews Sisters'),
    ('Ac-cent-tchu-ate the Positive', 1945, '2:46', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby & The Andrews Sisters'),
    ('Sioux City Sue', 1946, '2:47', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby & The Jesters'),
    ('Dinah', 1932, '2:56', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby & The Mills Brothers'),
    ("Oh, What a Beautiful Mornin'", 1943, '2:27', 'Bing Crosby - His Original Recordings', 'Pop', 'Bing Crosby & Trudy Erwin'),
    ('Birthday', 1987, '3:58', "Life's Too Good", 'Alternative Rock', 'The Sugarcubes'),
    ('Bitter Sweet Symphony', 1997, '5:58', 'Urban Hymns', 'Alternative Rock', 'The Verve'),
    ('In a Mist', 1927, '3:00', 'In a Mist', 'Jazz', 'Bix Beiderbecke'),
    ('Army of Me', 1995, '3:55', 'Post', 'Alternative Rock', 'Bjork')
]

modified_songs = []
for song in songs:
    song_list = list(song)
    time = song_list[2].replace(":", ".")
    time = float(time)
    song_list[2] = time
    song_list[2], song_list[3] = song_list[3], song_list[2]

    modified_songs.append(tuple(song_list))
   

modified_songs = tuple(modified_songs)
for song in modified_songs:
    print(song)