song_sample = [
    ("Nut Rocker", 2010, "Greatest Hits", 2.03, "Rock", "B Bumble & The Stingers"),
    ("Dance This Mess Around", 1979, "The B-52's", 4.35, "New Wave", "The B-52s"),
    ("Rock Lobster", 1978, "The B-52's", 6.50, "New Wave", "The B-52s"),
    ("Lava", 1979, "The B-52's", 4.54, "New Wave", "The B-52s"),
    ("There's A Moon In The Sky Called The Moon", 1979, "The B-52's", 4.58, "New Wave", "The B-52s"),
    ("Hero Worship", 1979, "The B-52's", 4.09, "New Wave", "The B-52s"),
    ("Funplex", 2008, "Funplex", 4.05, "Alternative Rock", "The B-52s"),
    ("Love Shack", 1989, "Cosmic Thing", 5.21, "Pop Rock", "The B-52s"),
    ("52 Girls", 1979, "The B-52's", 3.34, "New Wave", "The B-52s"),
    ("Roam", 1989, "Cosmic Thing", 4.54, "Pop Rock", "The B-52s"),
    ("6060-842", 1979, "The B-52's", 2.47, "New Wave", "The B-52s"),
    ("Planet Claire", 1979, "The B-52's", 4.35, "New Wave", "The B-52s"),
    ("Private Idaho", 1980, "Wild Planet", 3.34, "New Wave", "The B-52s"),
    ("High Heel Leather Boots", 2013, "Single Release", 3.54, "Indie Rock", "Baby Bee"),
    ("You Ain't Seen Nothing Yet", 1974, "Not Fragile", 3.37, "Rock", "Bachman-Turner Overdrive"),
    ("Takin' Care of Business", 1973, "Bachman-Turner Overdrive II", 4.49, "Rock", "Bachman-Turner Overdrive"),
    ("Let It Ride", 1973, "Bachman-Turner Overdrive II", 4.23, "Rock", "Bachman-Turner Overdrive"),
    ("Roll On Down the Highway", 1974, "Not Fragile", 3.57, "Rock", "Bachman-Turner Overdrive"),
    ("Hey You", 1975, "Four Wheel Drive", 3.36, "Rock", "Bachman-Turner Overdrive"),
    ("Everybody (Backstreet's Back)", 1997, "Backstreet's Back", 4.46, "Pop", "Backstreet Boys"),
    ("Feel Like Makin' Love", 1975, "Straight Shooter", 5.12, "Hard Rock", "Bad Company"),
    ("Shooting Star", 1975, "Straight Shooter", 6.17, "Hard Rock", "Bad Company"),
    ("Rock 'N' Roll Fantasy", 1979, "Desolation Angels", 3.20, "Hard Rock", "Bad Company"),
    ("Movin' On", 1974, "Bad Company", 3.24, "Hard Rock", "Bad Company"),
    ("Bad Company", 1974, "Bad Company", 4.50, "Hard Rock", "Bad Company"),
    ("Can't Get Enough", 1974, "Bad Company", 4.16, "Hard Rock", "Bad Company"),
    ("Runnin' With The Pack", 1976, "Runnin' With The Pack", 5.18, "Hard Rock", "Bad Company"),
    ("21st Century (Digital Boy)", 1990, "Stranger Than Fiction", 2.48, "Punk Rock", "Bad Religion"),
    ("Cardiac Arrest", 2014, "Language & Perspective", 3.51, "Indie Rock", "Bad Suns"),
    ("Come And Get It", 1969, "Magic Christian Music", 2.21, "Rock", "Badfinger"),
    ("Day After Day", 1971, "Straight Up", 3.10, "Rock", "Badfinger"),
    ("Carry On Til Tomorrow", 1970, "Magic Christian Music", 4.46, "Rock", "Badfinger"),
    ("No Matter What", 1970, "No Dice", 3.00, "Rock", "Badfinger"),
    ("The Name Of The Game", 1971, "Straight Up", 4.54, "Rock", "Badfinger"),
    ("Baby Blue", 1971, "Straight Up", 3.37, "Rock", "Badfinger"),
    ("Believe Me", 1970, "No Dice", 2.00, "Rock", "Badfinger"),
    ("Without You", 1970, "No Dice", 4.43, "Rock", "Badfinger"),
    ("Stone on the Water", 2000, "The Hour of Bewilderbeast", 4.15, "Indie Rock", "Badly Drawn Boy"),
    ("The Shining", 2000, "The Hour of Bewilderbeast", 5.18, "Indie Rock", "Badly Drawn Boy"),
    ("Disillusion", 2000, "The Hour of Bewilderbeast", 5.29, "Indie Rock", "Badly Drawn Boy"),
    ("Something to Talk About", 2002, "About a Boy", 3.35, "Indie Rock", "Badly Drawn Boy"),
    ("Once Around the Block", 1999, "The Hour of Bewilderbeast", 3.45, "Indie Rock", "Badly Drawn Boy"),
    ("Caught Me Thinking", 2012, "Barchords", 3.35, "Indie Folk", "Bahamas"),
    ("I Got You Babe", 2012, "Barchords", 2.49, "Indie Folk", "Bahamas"),
    ("Sister of Pearl", 2015, "The Names", 3.32, "Synth-pop", "Baio"),
    ("Tweedlee Dee", 1954, "Single Release", 3.10, "Rhythm and Blues", "LaVern Baker"),
    ("Jim Dandy", 1956, "Single Release", 2.12, "Rhythm and Blues", "LaVern Baker"),
    ("Gimme A Pigfoot", 1958, "Single Release", 2.08, "Rhythm and Blues", "LaVern Baker"),
    ("Got The Bottle Up And Gone", 1953, "Single Release", 2.28, "Rhythm and Blues", "LaVern Baker"),
    ("So High So Low", 2014, "Single Release", 3.55, "Indie Rock", "Barcelona"),
    ("Please Don't Go", 1979, "Single Release", 3.18, "Disco", "KC and the Sunshine Band"),
    ("Keep It Comin' Love", 1976, "Part 3", 4.27, "Disco", "KC and the Sunshine Band"),
    ("That's the Way (I Like It)", 1975, "KC and the Sunshine Band", 3.04, "Disco", "KC and the Sunshine Band"),
    ("Boogie Shoes", 1978, "KC and the Sunshine Band", 2.17, "Disco", "KC and the Sunshine Band"),
    ("I'm Your Boogie Man", 1976, "Part 3", 4.00, "Disco", "KC and the Sunshine Band"),
    ("Get Down Tonight", 1975, "KC and the Sunshine Band", 3.12, "Disco", "KC and the Sunshine Band"),
    ("All Over The World", 2017, "Rumors", 4.20, "Pop", "Bahamas"),
    ("Under The Boardwalk", 1964, "Single Release", 2.43, "R&B", "The Drifters"),
    ("This Magic Moment", 1960, "Single Release", 2.29, "R&B", "The Drifters"),
    ("On Broadway", 1963, "Single Release", 3.04, "R&B", "The Drifters"),
    ("Save The Last Dance For Me", 1960, "Single Release", 2.29, "R&B", "The Drifters"),
    ("Up On The Roof", 1962, "Single Release", 2.36, "R&B", "The Drifters"),
    ("There Goes My Baby", 1959, "Single Release", 2.12, "R&B", "The Drifters"),
    ("One Fine Day", 1963, "Single Release", 2.08, "R&B", "The Chiffons"),
    ("He's So Fine", 1963, "Single Release", 1.53, "R&B", "The Chiffons"),
    ("Sweet Talkin' Guy", 1966, "Single Release", 2.26, "R&B", "The Chiffons"),
    ("Just One Look", 1963, "Single Release", 2.30, "R&B", "Doris Troy"),
    ("Whatcha Gonna Do About It", 1965, "Single Release", 1.58, "R&B", "Doris Troy"),
    ("Wishin' and Hopin'", 1963, "Single Release", 2.59, "R&B", "Dionne Warwick"),
    ("Walk On By", 1964, "Make Way for Dionne Warwick", 2.55, "R&B", "Dionne Warwick"),
    ("I Say A Little Prayer", 1967, "Single Release", 3.03, "R&B", "Dionne Warwick"),
    ("Do You Know The Way To San Jose", 1968, "Single Release", 2.58, "R&B", "Dionne Warwick"),
    ("Don't Make Me Over", 1962, "Presenting Dionne Warwick", 2.46, "R&B", "Dionne Warwick"),
    ("Alfie", 1967, "Single Release", 2.45, "R&B", "Dionne Warwick"),
    ("Riders on the Storm", 1971, "L.A. Woman", 7.09, "Rock", "The Doors"),
    ("Break On Through (To The Other Side)", 1967, "The Doors", 2.29, "Rock", "The Doors"),
    ("Light My Fire", 1967, "The Doors", 7.06, "Rock", "The Doors"),
    ("Love Her Madly", 1971, "L.A. Woman", 3.20, "Rock", "The Doors"),
    ("People Are Strange", 1967, "Strange Days", 2.12, "Rock", "The Doors"),
    ("Touch Me", 1968, "The Soft Parade", 3.12, "Rock", "The Doors"),
    ("Hello, I Love You", 1968, "Waiting for the Sun", 2.16, "Rock", "The Doors"),
    ("The End", 1967, "The Doors", 11.41, "Rock", "The Doors"),
    ("L.A. Woman", 1971, "L.A. Woman", 7.49, "Rock", "The Doors"),
    ("Roadhouse Blues", 1970, "Morrison Hotel", 4.04, "Rock", "The Doors"),
    ("Don't Stop Believin'", 1981, "Escape", 4.10, "Rock", "Journey"),
    ("Any Way You Want It", 1980, "Departure", 3.22, "Rock", "Journey"),
    ("Wheel in the Sky", 1978, "Infinity", 4.12, "Rock", "Journey"),
    ("Faithfully", 1983, "Frontiers", 4.26, "Rock", "Journey"),
    ("Separate Ways (Worlds Apart)", 1983, "Frontiers", 5.25, "Rock", "Journey"),
    ("Open Arms", 1981, "Escape", 3.19, "Rock", "Journey"),
    ("Lovin', Touchin', Squeezin'", 1979, "Evolution", 3.54, "Rock", "Journey"),
    ("Who's Crying Now", 1981, "Escape", 5.01, "Rock", "Journey"),
    ("Stone In Love", 1981, "Escape", 4.25, "Rock", "Journey"),
    ("Send Her My Love", 1983, "Frontiers", 3.55, "Rock", "Journey"),
    ("Lights", 1978, "Infinity", 3.10, "Rock", "Journey"),
    ("Girl Can't Help It", 1986, "Raised on Radio", 3.50, "Rock", "Journey"),
    ("Mad World", 1982, "The Hurting", 3.31, "New Wave", "Tears for Fears"),
    ("Release", 1991, "Ten", 4.30, "Grunge", "Pearl Jam"),
    ("Fame", 1975, "Young Americans", 4.16, "Rock", "David Bowie"),
    ("Crazy In Love", 2003, "Dangerously in Love", 3.56, "R&B", "Beyoncé"),
    ("Close To Me", 1985, "The Head on the Door", 3.22, "Post-Punk", "The Cure"),
    ("1977", 2010, "1977", 3.34, "Hip Hop", "Ana Tijoux"),
    ("I Would Die 4 U", 1984, "Purple Rain", 2.51, "Pop", "Prince"),
    ("West End Girls", 1984, "Please", 4.45, "Synth-pop", "Pet Shop Boys"),
    ("Wildflowers", 1994, "Wildflowers", 3.11, "Rock", "Tom Petty"),
    ("No Surprises", 1997, "OK Computer", 3.51, "Alternative", "Radiohead"),
    ("Linger", 1993, "Everybody Else Is Doing It, So Why Can't We?", 4.34, "Alternative Rock", "The Cranberries"),
    ("That's Entertainment", 1980, "Sound Affects", 3.35, "Punk Rock", "The Jam"),
    ("Save Me", 1999, "Magnolia: Music from the Motion Picture", 4.35, "Indie Rock", "Aimee Mann"),
    ("Buggin Out", 1991, "The Low End Theory", 3.38, "Hip Hop", "A Tribe Called Quest"),
    ("The Day I Tried To Live", 1994, "Superunknown", 5.19, "Grunge", "Soundgarden"),
    ("Rudie Can't Fail", 1979, "London Calling", 3.28, "Punk", "The Clash"),
    ("Institutionalized", 1983, "Suicidal Tendencies", 3.50, "Punk", "Suicidal Tendencies"),
    ("One Way or Another", 1978, "Parallel Lines", 3.27, "New Wave", "Blondie"),
    ("Mayonnaise", 1993, "Siamese Dream", 5.50, "Alternative Rock", "Smashing Pumpkins"),
    ("It Was a Good Day", 1992, "The Predator", 4.20, "Hip Hop", "Ice Cube"),
    ("Chaise Longue", 2021, "Wet Leg", 3.11, "Indie Rock", "Wet Leg"),
    ("Head Over Heels", 1985, "Songs from the Big Chair", 4.14, "New Wave", "Tears For Fears"),
    ("Uncertain Smile", 1983, "Soul Mining", 5.01, "Alternative Rock", "The The"),
    ("Disorder", 1979, "Unknown Pleasures", 3.29, "Post-Punk", "Joy Division"),
    ("Don't Delete the Kisses", 2017, "Visions of a Life", 4.17, "Indie Rock", "Wolf Alice"),
    ("Always Love", 2005, "The Weight Is a Gift", 3.49, "Alternative Rock", "Nada Surf"),
    ("Superman", 1986, "Life's Rich Pageant", 2.53, "Alternative Rock", "R.E.M."),
    ("Me Myself and I", 1989, "3 Feet High and Rising", 3.40, "Hip Hop", "De La Soul"),
    ("Godless", 2000, "Thirteen Tales from Urban Bohemia", 4.36, "Alternative Rock", "Dandy Warhols"),
    ("Seasons", 2014, "Singles", 3.33, "Synth-pop", "Future Islands"),
    ("Rusty Cage", 1991, "Badmotorfinger", 4.26, "Grunge", "Soundgarden"),
    ("Sister Nancy", 1982, "One, Two", 3.22, "Reggae", "Bam Bam"),
    ("Desire Lines", 2010, "Halcyon Digest", 5.43, "Indie Rock", "Deerhunter"),
    ("Angel", 1998, "Mezzanine", 6.18, "Trip Hop", "Massive Attack"),
    ("River of Deceit", 1995, "Above", 5.03, "Grunge", "Mad Season"),
    ("She's Lost Control", 1979, "Unknown Pleasures", 3.57, "Post-Punk", "Joy Division"),
    ("One Big Holiday", 2003, "It Still Moves", 5.21, "Southern Rock", "My Morning Jacket"),
    ("Alison", 1993, "Souvlaki", 3.51, "Shoegaze", "Slowdive"),
    ("March of the Pigs", 1994, "The Downward Spiral", 2.54, "Industrial Rock", "Nine Inch Nails"),
    ("Master of Puppets", 1986, "Master of Puppets", 8.35, "Thrash Metal", "Metallica"),
    ("Heads Will Roll", 2009, "It's Blitz!", 3.41, "Indie Rock", "Yeah Yeah Yeahs"),
    ("The Plan", 1997, "Perfect from Now On", 4.21, "Indie Rock", "Built To Spill"),
    ("Touch of Gray", 1987, "In the Dark", 5.50, "Rock", "Grateful Dead"),
    ("Safe European Home", 1978, "Give 'Em Enough Rope", 3.50, "Punk Rock", "The Clash"),
    ("Not Too Soon", 1991, "The Real Ramona", 3.52, "Alternative Rock", "Throwing Muses"),
    ("2 Wicky", 1996, "A New Stereophonic Sound Spectacular", 4.44, "Trip Hop", "Hooverphonic"),
    ("Roxanne", 1978, "Outlandos d'Amour", 3.12, "New Wave", "The Police"),
    ("Funkier Than a Mosquito's Tweeter", 1974, "It Is Finished", 5.20, "Funk", "Nina Simone"),
    ("Pressure Drop", 1973, "Monkey Man", 3.46, "Reggae", "Toots and the Maytals"),
    ("The Rain Song", 1973, "Houses of the Holy", 7.39, "Rock", "Led Zeppelin"),
    ("Lost in the Supermarket", 1979, "London Calling", 3.47, "Punk Rock", "The Clash"),
    ("Rhiannon", 1975, "Fleetwood Mac", 4.11, "Rock", "Fleetwood Mac"),
    ("Talking About a Revolution", 1988, "Tracy Chapman", 2.38, "Folk", "Tracy Chapman"),
    ("Orange Sky", 2002, "Time Without Consequence", 5.32, "Indie Folk", "Alexi Murdoch"),
    ("Mercy Mercy Me", 1971, "What's Going On", 3.14, "Soul", "Marvin Gaye"),
    ("Rid of Me", 1993, "Rid of Me", 4.28, "Alternative Rock", "PJ Harvey"),
    ("Every Little Thing She Does is Magic", 1981, "Ghost in the Machine", 4.20, "New Wave", "The Police"),
    ("The Modern Leper", 2008, "The Midnight Organ Fight", 3.34, "Indie Rock", "Frightened Rabbit"),
    ("Ordinary World", 1993, "The Wedding Album", 4.41, "Pop Rock", "Duran Duran"),
    ("Sour Times", 1994, "Dummy", 4.11, "Trip Hop", "Portishead"),
    ("One More Hour", 1997, "Dig Me Out", 4.05, "Indie Rock", "Sleater Kinney"),
    ("Guns of Brixton", 1979, "London Calling", 3.07, "Reggae", "The Clash"),
    ("Wildfires", 2022, "N/A", 4.01, "Alternative", "Sault"),
    ("White Winter Hymnal", 2008, "Fleet Foxes", 2.27, "Indie Folk", "Fleet Foxes"),
    ("Grace", 1994, "Grace", 5.22, "Rock", "Jeff Buckley"),
    ("In My Time of Dying", 1975, "Physical Graffiti", 11.06, "Hard Rock", "Led Zeppelin"),
    ("Cities in Dust", 1985, "Tinderbox", 3.52, "New Wave", "Siouxsie and the Banshees"),
    ("Don't Look Back In Anger", 1995, "(What's the Story) Morning Glory?", 4.48, "Britpop", "Oasis"),
    ("Dig Me Out", 1997, "Dig Me Out", 2.40, "Indie Rock", "Sleater Kinney"),
    ("Good Morning Captain", 1991, "Spiderland", 7.39, "Post-Hardcore", "Slint"),
    ("Car", 1994, "There's Nothing Wrong with Love", 4.31, "Indie Rock", "Built to Spill"),
    ("Space Oddity", 1969, "David Bowie", 5.14, "Rock", "David Bowie"),
    ("The Killing Moon", 1984, "Ocean Rain", 5.45, "Post-Punk", "Echo & the Bunnymen"),
    ("Midnight City", 2011, "Hurry Up, We're Dreaming", 4.04, "Synth-pop", "M83"),
    ("Burning Down the House", 1983, "Speaking in Tongues", 4.01, "New Wave", "Talking Heads"),
    ("One", 1991, "Achtung Baby", 4.36, "Rock", "U2"),
    ("Zero", 1995, "Mellon Collie and the Infinite Sadness", 2.40, "Alternative Rock", "Smashing Pumpkins"),
    ("Once In A Lifetime", 1980, "Remain in Light", 4.19, "New Wave", "Talking Heads"),
    ("On Melancholy Hill", 2010, "Plastic Beach", 3.53, "Alternative Rock", "Gorillaz"),
    ("Step", 2012, "Days Are Gone", 4.09, "Indie Pop", "HAIM"),
    ("Strange Overtones", 2008, "Everything That Happens Will Happen Today", 4.17, "Electronic", "David Byrne & Brian Eno"),
    ("Digital Love", 2001, "Discovery", 5.01, "Electropop", "Daft Punk"),
    ("Blinding Lights", 2019, "After Hours", 3.20, "Synth-pop", "The Weeknd"),
    ("Gimme Shelter", 1969, "Let It Bleed", 4.31, "Rock", "The Rolling Stones"),
    ("Kashmir", 1975, "Physical Graffiti", 8.32, "Rock", "Led Zeppelin"),
    ("New Slang", 2001, "Oh, Inverted World", 3.51, "Indie Rock", "The Shins"),
    ("I Wanna Be Adored", 1989, "The Stone Roses", 4.52, "Alternative Rock", "The Stone Roses"),
    ("The Revolution Will Not Be Televised", 1971, "Small Talk at 125th and Lenox", 3.07, "Spoken Word", "Gil Scott-Heron"),
    ("Dissolve Me", 2012, "An Awesome Wave", 3.59, "Indie Rock", "alt-J"),
    ("Across 110th Street", 1972, "Across 110th Street", 3.48, "Soul", "Bobby Womack"),
    ("Move On Up", 1970, "Curtis", 8.50, "Soul", "Curtis Mayfield"),
    ("The Message", 1982, "The Message", 7.12, "Hip Hop", "Grandmaster Flash & The Furious Five"),
    ("Fools Gold", 1989, "Fool's Gold", 9.54, "Alternative Rock", "The Stone Roses"),
    ("Train in Vain", 1979, "London Calling", 3.10, "Punk Rock", "The Clash"),
    ("Just Like Heaven", 1987, "Kiss Me, Kiss Me, Kiss Me", 3.32, "Alternative Rock", "The Cure"),
    ("Atmosphere", 1980, "Atmosphere", 4.09, "Post-Punk", "Joy Division"),
    ("Take Me Out", 2004, "Franz Ferdinand", 3.57, "Indie Rock", "Franz Ferdinand"),
    ("Crush", 1998, "This Is My Truth Tell Me Yours", 4.34, "Alternative Rock", "Manic Street Preachers"),
    ("D.A.N.C.E.", 2007, "Cross", 4.02, "Electro House", "Justice"),
    ("Lebanese Blonde", 1999, "The Mirror Conspiracy", 4.47, "Downtempo", "Thievery Corporation"),
    ("Under Pressure", 1981, "Hot Space", 4.04, "Pop Rock", "Queen & David Bowie"),
    ("Your Silent Face", 1983, "Power, Corruption & Lies", 5.59, "New Wave", "New Order"),
    ("Take Five", 1959, "Time Out", 5.24, "Jazz", "The Dave Brubeck Quartet"),
    ("Panama", 1984, "1984", 3.30, "Hard Rock", "Van Halen"),
    ("Sunny Afternoon", 1966, "Face to Face", 3.36, "Rock", "The Kinks"),
    ("Good Times Bad Times", 1969, "Led Zeppelin", 2.46, "Rock", "Led Zeppelin"),
    ("Uptight (Everything's Alright)", 1965, "Up-Tight", 2.52, "Soul", "Stevie Wonder"),
    ("Summertime Blues", 1958, "Single release only", 2.01, "Rock and Roll", "Eddie Cochran"),
    ("Tin Soldier", 1967, "Small Faces", 3.20, "Rock", "Small Faces"),
    ("Let Forever Be", 1999, "Surrender", 3.56, "Big Beat", "The Chemical Brothers"),
    ("Groove Is in the Heart", 1990, "World Clique", 3.53, "House", "Deee-Lite"),
    ("This Is the One", 1989, "The Stone Roses", 4.58, "Alternative Rock", "The Stone Roses"),
    ("Temptation", 1982, "Temptation", 8.47, "New Wave", "New Order"),
    ("I'm Waiting for the Man", 1967, "The Velvet Underground & Nico", 4.38, "Proto-Punk", "The Velvet Underground"),
    ("Teardrop", 1998, "Mezzanine", 5.29, "Trip Hop", "Massive Attack"),
    ("The Ghost Inside", 2004, "Good Apollo, I'm Burning Star IV, Volume One: From Fear Through the Eyes of Madness", 3.39, "Alternative Rock", "Coheed and Cambria"),
    ("Sweet Jane", 1970, "Loaded", 3.17, "Rock", "The Velvet Underground"),
    ("Lust for Life", 1977, "Lust for Life", 5.13, "Rock", "Iggy Pop"),
    ("Song 2", 1997, "Blur", 2.02, "Alternative Rock", "Blur"),
    ("Ghost Town", 1981, "The Singles Collection 1967–1970", 3.40, "Reggae", "The Specials"),
    ("You Can't Always Get What You Want", 1969, "Let It Bleed", 7.28, "Rock", "The Rolling Stones"),
    ("Born Slippy .NUXX", 1995, "Born Slippy", 9.43, "Techno", "Underworld"),
    ("When the Levee Breaks", 1971, "Led Zeppelin IV", 7.08, "Blues Rock", "Led Zeppelin"),
    ("Shake Some Action", 1976, "Shake Some Action", 4.32, "Power Pop", "Flamin' Groovies"),
    ("Out of Time", 1991, "Out of Time", 4.27, "Alternative Rock", "R.E.M."),
    ("You're So Vain", 1972, "No Secrets", 4.19, "Soft Rock", "Carly Simon"),
    ("Ch-Check It Out", 2004, "To the 5 Boroughs", 3.12, "Hip Hop", "Beastie Boys"),
    ("Jigsaw Falling Into Place", 2007, "In Rainbows", 4.09, "Alternative Rock", "Radiohead"),
    ("Electric Feel", 2007, "Oracular Spectacular", 3.49, "Indie Pop", "MGMT"),
    ("Life on Mars?", 1971, "Hunky Dory", 3.54, "Rock", "David Bowie"),
    ("Bohemian Like You", 2000, "Thirteen Tales from Urban Bohemia", 3.32, "Alternative Rock", "The Dandy Warhols"),
    ("The Number of the Beast", 1982, "The Number of the Beast", 4.50, "Heavy Metal", "Iron Maiden"),
    ("Teen Age Riot", 1988, "Daydream Nation", 6.57, "Alternative Rock", "Sonic Youth"),
    ("The Man Who Sold the World", 1970, "The Man Who Sold the World", 3.55, "Rock", "David Bowie"),
    ("Hysteria", 1987, "Hysteria", 5.54, "Hard Rock", "Def Leppard"),
    ("Road to Nowhere", 1985, "Little Creatures", 4.20, "New Wave", "Talking Heads"),
    ("Out of Control", 2004, "Antics", 4.44, "Indie Rock", "Interpol"),
    ("My Name Is Jonas", 1994, "Weezer", 3.24, "Alternative Rock", "Weezer"),
    ("I Fought the Law", 1977, "The Clash", 2.39, "Punk Rock", "The Clash"),
    ("Heroes", 1977, "Heroes", 6.10, "Art Rock", "David Bowie"),
    ("Ceremony", 1981, "Single release only", 4.37, "Post-Punk", "New Order"),
    ("It's Tricky", 1986, "Raising Hell", 3.03, "Hip Hop", "Run-D.M.C."),
    ("Is This It", 2001, "Is This It", 2.35, "Indie Rock", "The Strokes"),
    ("Unfinished Sympathy", 1991, "Blue Lines", 5.08, "Trip Hop", "Massive Attack"),
    ("Starry Eyes", 1977, "The Only Ones", 2.29, "Power Pop", "The Only Ones"),
    ("E-Pro", 2005, "Guero", 3.26, "Alternative Rock", "Beck"),
    ("Ball and Biscuit", 2003, "Elephant", 7.19, "Blues Rock", "The White Stripes"),
    ("Sour Times", 1994, "Dummy", 4.11, "Trip Hop", "Portishead"),
    ("Running Up That Hill", 1985, "Hounds of Love", 5.00, "Art Pop", "Kate Bush"),
    ("Gangsters", 1979, "Single release only", 2.48, "2 Tone", "The Specials"),
    ("Bitter Sweet Symphony", 1997, "Urban Hymns", 5.58, "Alternative Rock", "The Verve"),
    ("Go Your Own Way", 1977, "Rumours", 3.43, "Rock", "Fleetwood Mac"),
    ("Sleeping Powder", 2017, "N/A", 3.04, "Alternative Rock", "Gorillaz"),
    ("Atrocity Exhibition", 1980, "Closer", 6.06, "Post-Punk", "Joy Division"),
    ("Misirlou", 1962, "Single release only", 2.16, "Surf Rock", "Dick Dale"),
    ("Golden Brown", 1981, "La Folie", 3.27, "New Wave", "The Stranglers"),
    ("California Dreamin'", 1965, "If You Can Believe Your Eyes and Ears", 2.42, "Folk Rock", "The Mamas & the Papas"),
    ("To Here Knows When", 1991, "Loveless", 5.31, "Shoegaze", "My Bloody Valentine"),
    ("Radio Free Europe", 1983, "Murmur", 4.06, "Alternative Rock", "R.E.M."),
    ("Where Is My Mind?", 1988, "Surfer Rosa", 3.53, "Alternative Rock", "Pixies"),
    ("Love Will Tear Us Apart", 1980, "Single release only", 3.25, "Post-Punk", "Joy Division"),
    ("Transmission", 1979, "Single release only", 3.36, "Post-Punk", "Joy Division"),
    ("I Melt with You", 1982, "After the Snow", 4.12, "New Wave", "Modern English"),
    ("Should I Stay or Should I Go", 1982, "Combat Rock", 3.07, "Punk Rock", "The Clash"),
    ("The Passenger", 1977, "Lust for Life", 4.41, "Rock", "Iggy Pop"),
    ("A Forest", 1980, "Seventeen Seconds", 5.55, "Post-Punk", "The Cure"),
    ("Maps", 2003, "Fever to Tell", 3.39, "Indie Rock", "Yeah Yeah Yeahs"),
    ("The Suburbs", 2010, "The Suburbs", 5.15, "Indie Rock", "Arcade Fire"),
    ("Jesus Walks", 2004, "The College Dropout", 3.13, "Hip Hop", "Kanye West"),
    ("This Charming Man", 1983, "This Charming Man", 2.43, "Indie Rock", "The Smiths"),
    ("Zero", 1995, "Mellon Collie and the Infinite Sadness", 2.40, "Alternative Rock", "Smashing Pumpkins"),
    ("Marquee Moon", 1977, "Marquee Moon", 10.40, "Art Punk", "Television"),
    ("Come As You Are", 1991, "Nevermind", 3.39, "Grunge", "Nirvana"),
    ("One Day Like This", 2008, "The Seldom Seen Kid", 6.34, "Alternative Rock", "Elbow"),
    ("Transmission", 1979, "Single release only", 3.36, "Post-Punk", "Joy Division"),
    ("I Melt with You", 1982, "After the Snow", 4.12, "New Wave", "Modern English"),
    ("Should I Stay or Should I Go", 1982, "Combat Rock", 3.07, "Punk Rock", "The Clash"),
    ("The Passenger", 1977, "Lust for Life", 4.41, "Rock", "Iggy Pop"),
    ("A Forest", 1980, "Seventeen Seconds", 5.55, "Post-Punk", "The Cure"),
    ("Maps", 2003, "Fever to Tell", 3.39, "Indie Rock", "Yeah Yeah Yeahs"),
    ("The Suburbs", 2010, "The Suburbs", 5.15, "Indie Rock", "Arcade Fire"),
    ("The Fresh Prince of Bel-Air", 1992, "N/A", 2.57, "Hip Hop", "Will Smith"),
    ("Drop It Like It's Hot", 2004, "R&G (Rhythm & Gangsta): The Masterpiece", 4.26, "Hip Hop", "Snoop Dogg"),
    ("London Calling", 1979, "London Calling", 3.20, "Punk Rock", "The Clash"),
    ("Genius of Love", 1981, "Tom Tom Club", 5.34, "New Wave", "Tom Tom Club"),
    ("Never Let Me Down Again", 1987, "Music for the Masses", 4.47, "Synth-pop", "Depeche Mode"),
    ("The Rat", 2004, "Bows + Arrows", 4.22, "Indie Rock", "The Walkmen"),
    ("Ever Fallen in Love (With Someone You Shouldn't've)", 1978, "Love Bites", 2.40, "Punk Rock", "Buzzcocks"),
    ("Once in a Lifetime", 1980, "Remain in Light", 4.19, "New Wave", "Talking Heads"),
    ("Lovefool", 1996, "First Band on the Moon", 3.18, "Pop Rock", "The Cardigans"),
    ("Rebel Rebel", 1974, "Diamond Dogs", 4.30, "Rock", "David Bowie"),
    ("New York, New York", 1977, "New York, New York", 3.31, "Pop", "Frank Sinatra"),
    ("Life's a Bitch", 1994, "Illmatic", 3.30, "Hip Hop", "Nas"),
    ("Heartbeats", 2002, "Deep Cuts", 2.40, "Indie Pop", "The Knife"),
    ("Neighborhood #1 (Tunnels)", 2004, "Funeral", 4.48, "Indie Rock", "Arcade Fire"),
    ("Should I Stay or Should I Go", 1982, "Combat Rock", 3.07, "Punk Rock", "The Clash"),
    ("No Surprises", 1997, "OK Computer", 3.48, "Alternative Rock", "Radiohead"),
    ("Hyper-Ballad", 1995, "Post", 5.21, "Electronic", "Björk"),
    ("Heart of Glass", 1978, "Parallel Lines", 4.33, "New Wave", "Blondie"),
    ("Teen Age Riot", 1988, "Daydream Nation", 6.57, "Alternative Rock", "Sonic Youth"),
    ("We Will Rock You", 1977, "News of the World", 2.01, "Rock", "Queen"),
    ("Once in a Lifetime", 1980, "Remain in Light", 4.19, "New Wave", "Talking Heads"),
    ("Blue Monday", 1983, "Blue Monday", 7.29, "Synth-pop", "New Order"),
    ("Straight Outta Compton", 1988, "Straight Outta Compton", 4.18, "Hip Hop", "N.W.A"),
    ("Transmission", 1979, "Single release only", 3.36, "Post-Punk", "Joy Division"),
    ("What's My Age Again?", 1999, "Enema of the State", 2.28, "Pop Punk", "Blink-182"),
    ("Teardrop", 1998, "Mezzanine", 5.29, "Trip Hop", "Massive Attack"),
    ("Sweet Jane", 1970, "Loaded", 3.17, "Rock", "The Velvet Underground"),
    ("Song 2", 1997, "Blur", 2.02, "Alternative Rock", "Blur"),
    ("Ghost Town", 1981, "The Singles Collection 1967–1970", 3.40, "Reggae", "The Specials"),
    ("You Can't Always Get What You Want", 1969, "Let It Bleed", 7.28, "Rock", "The Rolling Stones"),
    ("Psycho Killer", 1977, "Talking Heads: 77", 4.20, "New Wave", "Talking Heads"),
    ("Born Slippy .NUXX", 1995, "Born Slippy", 9.43, "Techno", "Underworld"),
    ("When the Levee Breaks", 1971, "Led Zeppelin IV", 7.08, "Blues Rock", "Led Zeppelin"),
    ("Shake Some Action", 1976, "Shake Some Action", 4.32, "Power Pop", "Flamin' Groovies"),
    ("Out of Time", 1991, "Out of Time", 4.27, "Alternative Rock", "R.E.M."),
    ("You're So Vain", 1972, "No Secrets", 4.19, "Soft Rock", "Carly Simon"),
    ("Ch-Check It Out", 2004, "To the 5 Boroughs", 3.12, "Hip Hop", "Beastie Boys"),
    ("Jigsaw Falling Into Place", 2007, "In Rainbows", 4.09, "Alternative Rock", "Radiohead"),
    ("Bad Reputation", 1980, "Bad Reputation", 2.44, "Hard Rock", "Joan Jett & The Blackhearts"),
    ("Sunday Bloody Sunday", 1983, "War", 4.38, "Rock", "U2"),
    ("Oh Bondage Up Yours!", 1977, "Germ Free Adolescents", 2.48, "Punk", "X Ray Spex"),
    ("Radio Clash", 1981, "This Is Radio Clash", 4.10, "Punk", "The Clash"),
    ("Unfinished Sympathy", 1991, "Blue Lines", 5.08, "Electronic", "Massive Attack"),
    ("Farewell Transmission", 2003, "Magnolia Electric Co", 7.22, "Indie Rock", "Songs: Ohia"),
    ("Not", 2019, "Two Hands", 3.24, "Indie Rock", "Big Thief"),
    ("Atlantic City", 1982, "Nebraska", 3.56, "Rock", "Bruce Springsteen"),
    ("Skinny Love", 2007, "For Emma, Forever Ago", 3.58, "Indie Folk", "Bon Iver"),
    ("Birthday", 1987, "Life's Too Good", 3.58, "Alternative Rock", "The Sugarcubes"),
    ("Blinding Lights", 2019, "After Hours", 3.20, "Pop", "The Weeknd"),
    ("Enter Sandman", 1991, "Metallica", 5.32, "Heavy Metal", "Metallica"),
    ("Decaptacon", 1999, "Le Tigre", 3.24, "Electro-Punk", "Le Tigre"),
    ("Lean on Me", 1972, "Still Bill", 4.18, "Soul", "Bill Withers"),
    ("Heart of Gold", 1972, "Harvest", 3.07, "Folk Rock", "Neil Young"),
    ("New Slang", 2001, "Oh, Inverted World", 3.51, "Indie Rock", "The Shins"),
    ("Rehab", 2006, "Back to Black", 3.35, "Soul", "Amy Winehouse"),
    ("Wonderwall", 1995, "What's the Story Morning Glory", 4.18, "Britpop", "Oasis"),
    ("Running Up That Hill", 1985, "Hounds of Love", 4.57, "Alternative Rock", "Kate Bush"),
    ("Under Pressure", 1981, "Hot Space", 4.08, "Rock", "Queen & David Bowie"),
    ("Where Is My Mind?", 1988, "Surfer Rosa", 3.53, "Alternative Rock", "Pixies"),
    ("Bohemian Rhapsody", 1975, "A Night at the Opera", 5.55, "Rock", "Queen"),
    ("Fight the Power", 1989, "Fear of a Black Planet", 4.42, "Hip Hop", "Public Enemy"),
    ("All Apologies", 1993, "In Utero", 3.51, "Grunge", "Nirvana"),
    ("This Is the Day", 1983, "Soul Mining", 4.56, "Post-Punk", "The The"),
    ("Jolene", 1974, "Jolene", 2.41, "Country", "Dolly Parton"),
    ("Idioteque", 2000, "Kid A", 5.09, "Electronic", "Radiohead"),
    ("Alive", 1991, "Ten", 5.41, "Grunge", "Pearl Jam"),
    ("Maps", 2003, "Fever to Tell", 3.40, "Indie Rock", "Yeah Yeah Yeahs"),
    ("Dance Yourself Clean", 2010, "This Is Happening", 8.56, "Electronic", "LCD Soundsystem"),
    ("Paranoid Android", 1997, "OK Computer", 6.23, "Alternative Rock", "Radiohead"),
    ("God Save the Queen", 1977, "Never Mind the Bollocks, Here's the Sex Pistols", 3.19, "Punk Rock", "Sex Pistols"),
    ("September", 1978, "The Best of Earth, Wind & Fire, Vol. 1", 3.36, "R&B", "Earth, Wind & Fire"),
    ("Flashlight", 1978, "Funkentelechy Vs. the Placebo Syndrome", 5.46, "Funk", "Parliament"),
    ("Kiss", 1986, "Parade", 3.46, "Funk", "Prince"),
    ("In the Aeroplane Over the Sea", 1998, "In the Aeroplane Over the Sea", 3.22, "Indie Rock", "Neutral Milk Hotel"),
    ("Jesus, Etc.", 2002, "Yankee Hotel Foxtrot", 3.50, "Alternative Rock", "Wilco"),
    ("Age of Consent", 1983, "Power, Corruption & Lies", 5.16, "New Wave", "New Order"),
    ("Rock the Casbah", 1982, "Combat Rock", 3.42, "Rock", "The Clash"),
    ("Loser", 1993, "Mellow Gold", 3.55, "Alternative Rock", "Beck"),
    ("Ziggy Stardust", 1972, "The Rise and Fall of Ziggy Stardust and the Spiders from Mars", 3.13, "Glam Rock", "David Bowie"),
    ("Let's Go Crazy", 1984, "Purple Rain", 4.39, "Pop", "Prince"),
    ("Feel Good Inc.", 2005, "Demon Days", 3.41, "Alternative Rock", "Gorillaz"),
    ("Seven Nation Army", 2003, "Elephant", 3.51, "Rock", "The White Stripes"),
    ("Redemption Song", 1980, "Uprising", 3.47, "Reggae", "Bob Marley & The Wailers"),
    ("Thriller", 1982, "Thriller", 5.57, "Pop", "Michael Jackson"),
    ("Fast Car", 1988, "Tracy Chapman", 4.56, "Folk Rock", "Tracy Chapman"),
    ("Fake Plastic Trees", 1995, "The Bends", 4.50, "Alternative Rock", "Radiohead"),
    ("What's Going On", 1971, "What's Going On", 3.53, "Soul", "Marvin Gaye"),
    ("Ashes to Ashes", 1980, "Scary Monsters (And Super Creeps)", 4.23, "Art Rock", "David Bowie"),
    ("The Killing Moon", 1984, "Ocean Rain", 5.46, "Post-Punk", "Echo & The Bunnymen"),
    ("In Your Eyes", 1986, "So", 5.29, "Pop Rock", "Peter Gabriel"),
    ("Let Down", 1997, "OK Computer", 4.59, "Alternative Rock", "Radiohead"),
    ("Fascination Street", 1989, "Disintegration", 5.16, "Gothic Rock", "The Cure"),
    ("Fall on Me", 1986, "Lifes Rich Pageant", 2.50, "Alternative Rock", "R.E.M."),
    ("One", 1991, "Achtung Baby", 4.36, "Rock", "U2"),
    ("All Apologies", 1993, "In Utero", 3.51, "Grunge", "Nirvana"),
    ("Neighborhood #1 (Tunnels)", 2004, "Funeral", 4.48, "Indie Rock", "Arcade Fire"),
    ("Roadrunner", 1976, "The Modern Lovers", 4.05, "Proto-Punk", "The Modern Lovers"),
    ("Hurt", 1994, "The Downward Spiral", 6.13, "Industrial Rock", "Nine Inch Nails"),
    ("Such Great Heights", 2003, "Give Up", 4.26, "Indie Pop", "The Postal Service"),
    ("Wonderwall", 1995, "(What's the Story) Morning Glory?", 4.18, "Britpop", "Oasis"),
    ("Rehab", 2006, "Back to Black", 3.34, "Soul", "Amy Winehouse"),
    ("Transmission", 1979, "Unknown Pleasures", 3.36, "Post-Punk", "Joy Division"),
    ("Lust For Life", 1977, "Lust for Life", 5.12, "Rock", "Iggy Pop"),
    ("Stayin' Alive", 1977, "Saturday Night Fever", 4.45, "Disco", "Bee Gees"),
    ("Protection", 1994, "Protection", 7.53, "Trip Hop", "Massive Attack"),
    ("Lover, You Should've Come Over", 1994, "Grace", 6.43, "Alternative Rock", "Jeff Buckley"),
    ("Time", 1973, "The Dark Side of the Moon", 6.53, "Progressive Rock", "Pink Floyd"),
    ("Thirteen", 1972, "#1 Record", 2.34, "Power Pop", "Big Star"),
    ("Should I Stay or Should I Go", 1982, "Combat Rock", 3.09, "Punk Rock", "The Clash"),
    ("Pictures of You", 1989, "Disintegration", 7.28, "Gothic Rock", "The Cure"),
    ("Midnight City", 2011, "Hurry Up, We're Dreaming", 4.04, "Electronic", "M83"),
    ("Graceland", 1986, "Graceland", 4.51, "Folk Rock", "Paul Simon"),
    ("Anarchy in the U.K.", 1976, "Never Mind the Bollocks, Here's the Sex Pistols", 3.32, "Punk Rock", "Sex Pistols"),
    ("Debaser", 1989, "Doolittle", 2.52, "Alternative Rock", "Pixies"),
    ("The Whole of the Moon", 1985, "This Is the Sea", 5.01, "Alternative Rock", "The Waterboys"),
    ("Go Your Own Way", 1977, "Rumours", 3.38, "Rock", "Fleetwood Mac"),
    ("Losing My Edge", 2002, "LCD Soundsystem", 7.53, "Dance-punk", "LCD Soundsystem"),
    ("Call Me", 1980, "American Gigolo", 3.32, "New Wave", "Blondie"),
    ("Army of Me", 1995, "Post", 3.54, "Electronic", "Björk"),
    ("Song 2", 1997, "Blur", 2.01, "Alternative Rock", "Blur"),
    ("Blister in the Sun", 1983, "Violent Femmes", 2.25, "Folk Punk", "Violent Femmes"),
    ("It's the End of the World as We Know It (And I Feel Fine)", 1987, "Document", 4.05, "Alternative Rock", "R.E.M."),
    ("Live Forever", 1994, "(What's the Story) Morning Glory?", 4.36, "Britpop", "Oasis"),
    ("I Wanna Be Adored", 1989, "The Stone Roses", 4.52, "Alternative Rock", "The Stone Roses"),
    ("You Said Something", 2000, "Stories from the City, Stories from the Sea", 3.19, "Alternative Rock", "PJ Harvey"),
    ("Dear God", 1986, "Skylarking", 3.37, "Alternative Rock", "XTC"),
    ("Landslide", 1975, "Fleetwood Mac", 3.19, "Rock", "Fleetwood Mac"),
    ("Everybody Knows", 1988, "I'm Your Man", 5.37, "Folk Rock", "Leonard Cohen"),
    ("Left of the Dial", 1985, "Tim", 3.41, "Alternative Rock", "The Replacements"),
    ("Such Great Heights", 2003, "Give Up", 4.26, "Indie Pop", "The Postal Service"),
    ("Hurt", 1994, "The Downward Spiral", 6.14, "Industrial Rock", "Nine Inch Nails"),
    ("Roadrunner", 1976, "The Modern Lovers", 4.05, "Proto-Punk", "The Modern Lovers"),
    ("Neighborhood #1 (Tunnels)", 2004, "Funeral", 4.48, "Indie Rock", "Arcade Fire"),
    ("All Apologies", 1993, "In Utero", 3.51, "Grunge", "Nirvana"),
    ("One", 1991, "Achtung Baby", 4.36, "Rock", "U2"),
    ("Fall on Me", 1986, "Lifes Rich Pageant", 2.50, "Alternative Rock", "R.E.M."),
    ("Fascination Street", 1989, "Disintegration", 5.16, "Gothic Rock", "The Cure"),
    ("Let Down", 1997, "OK Computer", 4.59, "Alternative Rock", "Radiohead"),
    ("In Your Eyes", 1986, "So", 5.29, "Pop Rock", "Peter Gabriel"),
    ("The Killing Moon", 1984, "Ocean Rain", 5.46, "Post-Punk", "Echo & The Bunnymen"),
    ("Ashes to Ashes", 1980, "Scary Monsters (and Super Creeps)", 4.23, "Art Rock", "David Bowie"),
    ("What's Going On", 1971, "What's Going On", 3.53, "Soul", "Marvin Gaye"),
    ("Fake Plastic Trees", 1995, "The Bends", 4.50, "Alternative Rock", "Radiohead"),
    ("Fast Car", 1988, "Tracy Chapman", 4.56, "Folk Rock", "Tracy Chapman"),
    ("Thriller", 1982, "Thriller", 5.57, "Pop", "Michael Jackson"),
    ("Redemption Song", 1980, "Uprising", 3.47, "Reggae", "Bob Marley"),
    ("Seven Nation Army", 2003, "Elephant", 3.51, "Rock", "The White Stripes"),
    ("Feel Good Inc.", 2005, "Demon Days", 3.41, "Alternative Rock", "Gorillaz"),
    ("Let's Go Crazy", 1984, "Purple Rain", 4.39, "Pop", "Prince"),
    ("Ziggy Stardust", 1972, "The Rise and Fall of Ziggy Stardust and the Spiders from Mars", 3.13, "Glam Rock", "David Bowie"),
    ("Loser", 1993, "Mellow Gold", 3.55, "Alternative Rock", "Beck"),
    ("Rock the Casbah", 1982, "Combat Rock", 3.42, "Punk Rock", "The Clash"),
    ("Age of Consent", 1983, "Power, Corruption & Lies", 5.16, "New Wave", "New Order"),
    ("Jesus, Etc.", 2002, "Yankee Hotel Foxtrot", 3.50, "Alternative Rock", "Wilco"),
    ("In the Aeroplane Over the Sea", 1998, "In the Aeroplane Over the Sea", 3.22, "Indie Rock", "Neutral Milk Hotel"),
    ("Kiss", 1986, "Parade", 3.46, "Funk", "Prince"),
    ("Flashlight", 1978, "Funkentelechy Vs. the Placebo Syndrome", 5.46, "Funk", "Parliament"),
    ("September", 1978, "The Best of Earth, Wind & Fire, Vol. 1", 3.36, "R&B", "Earth, Wind & Fire"),
    ("God Save the Queen", 1977, "Never Mind the Bollocks, Here's the Sex Pistols", 3.19, "Punk Rock", "Sex Pistols"),
    ("Heartbeats", 2002, "Deep Cuts", 3.51, "Synth-pop", "The Knife"),
    ("My Girls", 2009, "Merriweather Post Pavilion", 5.41, "Psychedelic Pop", "Animal Collective"),
    ("Kashmir", 1975, "Physical Graffiti", 8.37, "Hard Rock", "Led Zeppelin"),
    ("Nightswimming", 1992, "Automatic for the People", 4.18, "Alternative Rock", "R.E.M."),
    ("Maps", 2003, "Fever to Tell", 3.40, "Indie Rock", "Yeah Yeah Yeahs"),
    ("Jane Says", 1988, "Nothing's Shocking", 4.52, "Alternative Rock", "Jane's Addiction"),
    ("Killing in the Name", 1992, "Rage Against the Machine", 5.14, "Rap Metal", "Rage Against the Machine"),
    ("Creep", 1992, "Pablo Honey", 3.59, "Alternative Rock", "Radiohead"),
    ("Wolf Like Me", 2006, "Return to Cookie Mountain", 4.39, "Indie Rock", "TV on the Radio"),
    ("This Is the Sea", 1985, "This Is the Sea", 6.29, "Alternative Rock", "The Waterboys"),
    ("Disintegration", 1989, "Disintegration", 8.23, "Gothic Rock", "The Cure"),
    ("Starman", 1972, "The Rise and Fall of Ziggy Stardust and the Spiders from Mars", 4.10, "Glam Rock", "David Bowie"),
    ("As", 1976, "Songs in the Key of Life", 7.08, "Soul", "Stevie Wonder"),
    ("Radio Free Europe", 1983, "Murmur", 4.06, "Alternative Rock", "R.E.M."),
    ("Chloe Dancer/Crown of Thorns", 1990, "Apple", 8.34, "Grunge", "Mother Love Bone"),
    ("Hallelujah", 1984, "Various Positions", 4.37, "Folk Rock", "Leonard Cohen"),
    ("Billie Jean", 1982, "Thriller", 4.54, "Pop", "Michael Jackson"),
    ("Carry the Zero", 1999, "Keep It Like a Secret", 5.44, "Indie Rock", "Built to Spill"),
    ("Heart of Glass", 1978, "Parallel Lines", 4.33, "Disco", "Blondie"),
    ("Fake Empire", 2007, "Boxer", 3.25, "Indie Rock", "The National"),
    ("Psycho Killer", 1977, "Talking Heads: 77", 4.19, "New Wave", "Talking Heads"),
    ("Everything In Its Right Place", 2000, "Kid A", 4.11, "Electronic", "Radiohead"),
    ("Teen Age Riot", 1988, "Daydream Nation", 6.57, "Alternative Rock", "Sonic Youth"),
    ("Walk on the Wild Side", 1972, "Transformer", 4.12, "Rock", "Lou Reed"),
    ("Where the Streets Have No Name", 1987, "The Joshua Tree", 5.37, "Rock", "U2"),
    ("Teardrop", 1998, "Mezzanine", 5.31, "Trip Hop", "Massive Attack"),
    ("Freedom! '90", 1990, "Listen Without Prejudice Vol. 1", 6.30, "Pop", "George Michael"),
    ("Sir Duke", 1976, "Songs in the Key of Life", 3.54, "Soul", "Stevie Wonder"),
    ("Train in Vain", 1979, "London Calling", 3.09, "Punk Rock", "The Clash"),
    ("This is the Day", 1983, "Soul Mining", 4.56, "New Wave", "The The"),
    ("Jolene", 1973, "Jolene", 2.41, "Country", "Dolly Parton"),
    ("Three Little Birds", 1977, "Exodus", 3.00, "Reggae", "Bob Marley & The Wailers"),
    ("Hey Ya!", 2003, "Speakerboxxx/The Love Below", 3.55, "Hip Hop", "Outkast"),
    ("Hounds of Love", 1985, "Hounds of Love", 3.02, "Pop", "Kate Bush"),
    ("The Rat", 2004, "Bows + Arrows", 4.21, "Indie Rock", "The Walkmen"),
    ("Dancing On My Own", 2010, "Body Talk Pt. 1", 4.49, "Pop", "Robyn"),
    ("Idioteque", 2000, "Kid A", 5.09, "Electronic", "Radiohead"),
    ("Enjoy the Silence", 1990, "Violator", 4.16, "Synth-Pop", "Depeche Mode"),
    ("Bitter Sweet Symphony", 1997, "Urban Hymns", 5.58, "Alternative Rock", "The Verve"),
    ("I Still Haven't Found What I'm Looking For", 1987, "The Joshua Tree", 4.37, "Rock", "U2"),
    ("Someone Great", 2007, "Sound of Silver", 6.25, "Electronic", "LCD Soundsystem"),
    ("Alive", 1991, "Ten", 5.41, "Grunge", "Pearl Jam"),
    ("Harvest Moon", 1992, "Harvest Moon", 5.03, "Folk Rock", "Neil Young"),
    ("Gloria: In Excelsis Deo", 1975, "Horses", 5.20, "Punk Rock", "Patti Smith"),
    ("Burning Down the House", 1983, "Speaking in Tongues", 4.02, "New Wave", "Talking Heads"),
    ("The Chain", 1977, "Rumours", 4.28, "Rock", "Fleetwood Mac"),
    ("Karma Police", 1997, "OK Computer", 4.21, "Alternative Rock", "Radiohead"),
    ("This Year", 2005, "The Sunset Tree", 3.52, "Indie Rock", "The Mountain Goats"),
    ("A Forest", 1980, "Seventeen Seconds", 5.55, "Post-Punk", "The Cure"),
    ("With or Without You", 1987, "The Joshua Tree", 4.56, "Rock", "U2"),
    ("Thunder Road", 1975, "Born to Run", 4.49, "Rock", "Bruce Springsteen"),
    ("Comfortably Numb", 1979, "The Wall", 6.21, "Progressive Rock", "Pink Floyd"),
    ("Don't Change", 1982, "Shabooh Shoobah", 4.24, "New Wave", "INXS"),
    ("Paper Planes", 2007, "Kala", 3.24, "Alternative Hip Hop", "M.I.A."),
    ("Can I Kick It?", 1990, "People's Instinctive Travels and the Paths of Rhythm", 4.12, "Hip Hop", "A Tribe Called Quest"),
    ("Hallelujah", 1994, "Grace", 6.53, "Alternative Rock", "Jeff Buckley"),
    ("Black", 1991, "Ten", 5.43, "Grunge", "Pearl Jam"),
    ("Ceremony", 1981, "Still", 4.23, "Post-Punk", "New Order"),
    ("Rebel Girl", 1993, "Pussy Whipped", 2.47, "Punk Rock", "Bikini Kill"),
    ("Marquee Moon", 1977, "Marquee Moon", 10.40, "Art Punk", "Television"),
    ("Fade Into You", 1993, "So Tonight That I Might See", 4.55, "Alternative Rock", "Mazzy Star"),
    ("Bad", 1984, "The Unforgettable Fire", 6.09, "Rock", "U2"),
    ("Tangled Up in Blue", 1975, "Blood on the Tracks", 5.42, "Folk Rock", "Bob Dylan"),
    ("Come As You Are", 1991, "Nevermind", 3.38, "Grunge", "Nirvana"),
    ("How Soon is Now?", 1985, "Meat Is Murder", 6.45, "Alternative Rock", "The Smiths"),
    ("Waiting Room", 1988, "13 Songs", 2.53, "Post-Hardcore", "Fugazi"),
    ("Life On Mars?", 1971, "Hunky Dory", 3.48, "Art Rock", "David Bowie"),
    ("Dreams", 1977, "Rumours", 4.17, "Rock", "Fleetwood Mac"),
    ("I Feel Love", 1977, "I Remember Yesterday", 5.53, "Disco", "Donna Summer"),
    ("Do You Realize??", 2002, "Yoshimi Battles the Pink Robots", 3.32, "Psychedelic Rock", "The Flaming Lips"),
    ("Everybody Wants to Rule the World", 1985, "Songs from the Big Chair", 4.11, "New Wave", "Tears For Fears"),
    ("Sabotage", 1994, "Ill Communication", 2.58, "Hip Hop", "Beastie Boys"),
    ("When Doves Cry", 1984, "Purple Rain", 5.54, "Pop", "Prince"),
    ("Just Like Heaven", 1987, "Kiss Me, Kiss Me, Kiss Me", 3.32, "Alternative Rock", "The Cure"),
    ("Born to Run", 1975, "Born to Run", 4.30, "Rock", "Bruce Springsteen"),
    ("Superstition", 1972, "Talking Book", 4.26, "Funk", "Stevie Wonder"),
    ("Wake Up", 2004, "Funeral", 5.35, "Indie Rock", "Arcade Fire"),
    ("Dance Yourself Clean", 2010, "This Is Happening", 8.56, "Dance-Punk", "LCD Soundsystem"),
    ("Wish You Were Here", 1975, "Wish You Were Here", 5.34, "Progressive Rock", "Pink Floyd"),
    ("Blue Monday", 1983, "Power, Corruption & Lies", 7.29, "New Wave", "New Order"),
    ("All My Friends", 2007, "Sound of Silver", 7.37, "Dance-Punk", "LCD Soundsystem"),
    ("Once in a Lifetime", 1980, "Remain in Light", 4.19, "New Wave", "Talking Heads"),
    ("London Calling", 1979, "London Calling", 3.20, "Punk Rock", "The Clash"),
    ("Lovely Day", 1977, "Menagerie", 4.15, "Soul", "Bill Withers"),
    ("Paranoid Android", 1997, "OK Computer", 6.23, "Alternative Rock", "Radiohead"),
    ("Under Pressure", 1981, "Hot Space", 4.08, "Rock", "Queen & David Bowie"),
    ("Running Up That Hill (A Deal with God)", 1985, "Hounds of Love", 4.57, "Pop", "Kate Bush"),
    ("Fight the Power", 1989, "Fear of a Black Planet", 4.42, "Hip Hop", "Public Enemy"),
    ("Where Is My Mind?", 1988, "Surfer Rosa", 3.53, "Alternative Rock", "Pixies"),
    ("Bohemian Rhapsody", 1975, "A Night at the Opera", 5.55, "Rock", "Queen"),
    ("Love Will Tear Us Apart", 1980, "Love Will Tear Us Apart", 3.25, "Post-Punk", "Joy Division"),
    ("Smells Like Teen Spirit", 1991, "Nevermind", 5.01, "Grunge", "Nirvana"),
    ("This Must Be the Place (Naive Melody)", 1983, "Speaking in Tongues", 4.56, "New Wave", "Talking Heads"),
    ("Purple Rain", 1984, "Purple Rain", 8.41, "Pop", "Prince"),
    ("Heroes", 1977, "Heroes", 6.07, "Rock", "David Bowie")

]



]

unique_songs = list(set(song_sample))

print(len(unique_songs))
print(len(song_sample))
print(sorted(unique_songs))