-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema artiststrackerdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `artiststrackerdb` ;

-- -----------------------------------------------------
-- Schema artiststrackerdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `artiststrackerdb` DEFAULT CHARACTER SET utf8 ;
USE `artiststrackerdb` ;

-- -----------------------------------------------------
-- Table `artist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `artist` ;

CREATE TABLE IF NOT EXISTS `artist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `image` VARCHAR(500) NULL DEFAULT 'default',
  `band` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `song`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `song` ;

CREATE TABLE IF NOT EXISTS `song` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `song_length` DOUBLE NULL,
  `genre` VARCHAR(45) NULL,
  `album_title` VARCHAR(45) NULL,
  `artist_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_song_artist_idx` (`artist_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_song_artist`
    FOREIGN KEY (`artist_id`)
    REFERENCES `artist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS artistsuser@localhost;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'artistsuser'@'localhost' IDENTIFIED BY 'artistsuser';

GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE * TO 'artistsuser'@'localhost';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `artist`
-- -----------------------------------------------------
START TRANSACTION;
USE `artiststrackerdb`;
INSERT INTO `artist` (`id`, `name`, `image`)
VALUES 
(1, '10cc', 'image_url_10cc'),
(2, '2Pac', 'image_url_2pac'),
(3, '50 Cent', 'image_url_50cent'),
(4, 'A', 'image_url_a'),
(5, 'A Thousand Horses', 'image_url_thousand_horses'),
(6, 'ABBA', 'image_url_abba'),
(7, 'ABC', 'image_url_abc'),
(8, 'Aerosmith', 'image_url_aerosmith'),
(9, 'Agnetha Fältskog', 'image_url_agnetha_faltskog'),
(10, 'Alan Jackson', 'image_url_alan_jackson'),
(11, 'Albert King', 'image_url_albert_king'),
(12, 'Alice Cooper', 'image_url_alice_cooper'),
(13, 'Alison Krauss', 'image_url_alison_krauss'),
(14, 'The All-American Rejects', 'image_url_all_american_rejects'),
(15, 'The Allman Brothers Band', 'image_url_allman_brothers_band'),
(16, 'Amy Winehouse', 'image_url_amy_winehouse'),
(17, 'Andre Rieu', 'image_url_andre_rieu'),
(18, 'Andrea Bocelli', 'image_url_andrea_bocelli'),
(19, 'Andrew W.K.', 'image_url_andrew_wk'),
(20, 'Anthrax', 'image_url_anthrax'),
(21, 'Antonio Carlos Jobim', 'image_url_antonio_carlos_jobim'),
(22, 'Apache Indian', 'image_url_apache_indian'),
(23, 'Arcade Fire', 'image_url_arcade_fire'),
(24, 'Ariana Grande', 'image_url_ariana_grande'),
(25, 'Arrested Development', 'image_url_arrested_development'),
(26, 'Ashley Campbell', 'image_url_ashley_campbell'),
(27, 'Astrud Gilberto', 'image_url_astrud_gilberto'),
(28, 'Aswad', 'image_url_aswad'),
(29, 'Atlanta Rhythm Section', 'image_url_atlanta_rhythm_section'),
(30, 'Audioslave', 'image_url_audioslave'),
(31, 'B.B. King', 'image_url_bb_king'),
(32, 'Badfinger', 'image_url_badfinger'),
(33, 'The Band', 'image_url_the_band'),
(34, 'Barclay James Harvest', 'image_url_barclay_james_harvest'),
(35, 'Barry White', 'image_url_barry_white'),
(36, 'The Beach Boys', 'image_url_beach_boys'),
(37, 'Beastie Boys', 'image_url_beastie_boys'),
(38, 'The Beatles', 'image_url_beatles'),
(39, 'Beck', 'image_url_beck'),
(40, 'Bee Gees', 'image_url_bee_gees'),
(41, 'Belinda Carlisle', 'image_url_belinda_carlisle'),
(42, 'Ben Harper', 'image_url_ben_harper'),
(43, 'Ben Howard', 'image_url_ben_howard'),
(44, 'Benny Andersson', 'image_url_benny_andersson'),
(45, 'Big Country', 'image_url_big_country'),
(46, 'Big Star', 'image_url_big_star'),
(47, 'Bill Evans', 'image_url_bill_evans'),
(48, 'Billie Eilish', 'image_url_billie_eilish'),
(49, 'Billie Holiday', 'image_url_billie_holiday'),
(50, 'Billy Currington', 'image_url_billy_currington'),
(51, 'Billy Fury', 'image_url_billy_fury'),
(52, 'Billy Preston', 'image_url_billy_preston'),
(53, 'Björk', 'image_url_bjork'),
(54, 'Black Eyed Peas', 'image_url_black_eyed_peas'),
(55, 'Black Sabbath', 'image_url_black_sabbath'),
(56, 'Black Uhuru', 'image_url_black_uhuru'),
(57, 'Blind Faith', 'image_url_blind_faith'),
(58, 'Blink-182', 'image_url_blink_182'),
(59, 'Blondie', 'image_url_blondie'),
(60, 'Blue Cheer', 'image_url_blue_cheer'),
(61, 'Bo Diddley', 'image_url_bo_diddley'),
(62, 'Bob Dylan', 'image_url_bob_dylan'),
(63, 'Bob Marley', 'image_url_bob_marley'),
(64, 'Bob Seger', 'image_url_bob_seger'),
(65, 'Bon Jovi', 'image_url_bon_jovi'),
(66, 'Bonnie Raitt', 'image_url_bonnie_raitt'),
(67, 'Booker T', 'image_url_booker_t'),
(68, 'Boyz II Men', 'image_url_boyz_ii_men'),
(69, 'Brantley Gilbert', 'image_url_brantley_gilbert'),
(70, 'Brenda Holloway', 'image_url_brenda_holloway'),
(71, 'Brian Eno', 'image_url_brian_eno'),
(72, 'The Brothers Johnson', 'image_url_brothers_johnson'),
(73, 'Bruce Springsteen', 'image_url_bruce_springsteen'),
(74, 'Bryan Adams', 'image_url_bryan_adams'),
(75, 'Bryan Ferry', 'image_url_bryan_ferry'),
(76, 'Buddy Guy', 'image_url_buddy_guy'),
(77, 'Buddy Holly', 'image_url_buddy_holly'),
(78, 'Burning Spear', 'image_url_burning_spear'),
(79, 'Burt Bacharach', 'image_url_burt_bacharach'),
(80, 'The Cadillac Three', 'image_url_cadillac_three'),
(81, 'Camel', 'image_url_camel'),
(82, 'Canned Heat', 'image_url_canned_heat'),
(83, 'Captain Beefheart', 'image_url_captain_beefheart'),
(84, 'Caravan', 'image_url_caravan'),
(85, 'Carpenters', 'image_url_carpenters'),
(86, 'Carrie Underwood', 'image_url_carrie_underwood'),
(87, 'Cat Stevens', 'image_url_cat_stevens'),
(88, 'Charlie Parker', 'image_url_charlie_parker'),
(89, 'Cheap Trick', 'image_url_cheap_trick'),
(90, 'The Chemical Brothers', 'image_url_chemical_brothers'),
(91, 'Cher', 'image_url_cher'),
(92, 'Chris Cornell', 'image_url_chris_cornell'),
(93, 'Chris Stapleton', 'image_url_chris_stapleton'),
(94, 'Chuck Berry', 'image_url_chuck_berry'),
(95, 'Cinderella', 'image_url_cinderella'),
(96, 'The Clash', 'image_url_clash'),
(97, 'Climax Blues Band', 'image_url_climax_blues_band'),
(98, 'Coleman Hawkins', 'image_url_coleman_hawkins'),
(99, 'Commodores', 'image_url_commodores'),
(100, 'Common', 'image_url_common'),
(101, 'The Common Linnets', 'image_url_common_linnets'),
(102, 'Corinne Bailey Rae', 'image_url_corinne_bailey_rae'),
(103, 'Count Basie', 'image_url_count_basie'),
(104, 'Counting Crows', 'image_url_counting_crows'),
(105, 'Craig Armstrong', 'image_url_craig_armstrong'),
(106, 'The Cranberries', 'image_url_cranberries'),
(107, 'Cream', 'image_url_cream'),
(108, 'Creedence Clearwater Revival', 'image_url_creedence_clearwater_revival'),
(109, 'Crowded House', 'image_url_crowded_house'),
(110, 'Culture Club', 'image_url_culture_club'),
(111, 'The Cure', 'image_url_cure'),
(112, 'Cutting Crew', 'image_url_cutting_crew'),
(113, 'D’Angelo', 'image_url_d_angelo'),
(114, 'DMX', 'image_url_dmx'),
(115, 'The Damned', 'image_url_damned'),
(116, 'Daniel Hope', 'image_url_daniel_hope'),
(117, 'Danny Wilson & Gary Clark', 'image_url_danny_wilson_gary_clark'),
(118, 'David Bowie', 'image_url_david_bowie'),
(119, 'Dean Martin', 'image_url_dean_martin'),
(120, 'Debarge', 'image_url_debarge'),
(121, 'Deep Purple', 'image_url_deep_purple'),
(122, 'Def Leppard', 'image_url_def_leppard'),
(123, 'Demi Lovato', 'image_url_demi_lovato'),
(124, 'Demis Roussos', 'image_url_demis_roussos'),
(125, 'Derek And The Dominos', 'image_url_derek_and_the_dominos'),
(126, 'Desmond Dekker', 'image_url_desmond_dekker'),
(127, 'Diana Krall', 'image_url_diana_krall'),
(128, 'Diana Ross', 'image_url_diana_ross'),
(129, 'Diana Ross & The Supremes', 'image_url_diana_ross_supremes'),
(130, 'Dierks Bentley', 'image_url_dierks_bentley'),
(131, 'Dinah Washington', 'image_url_dinah_washington'),
(132, 'Dio', 'image_url_dio'),
(133, 'Dire Straits', 'image_url_dire_straits'),
(134, 'Disclosure', 'image_url_disclosure'),
(135, 'Don Henley', 'image_url_don_henley'),
(136, 'Donna Summer', 'image_url_donna_summer'),
(137, 'The Doors', 'image_url_doors'),
(138, 'Dr Dre', 'image_url_dr_dre'),
(139, 'Drake', 'image_url_drake'),
(140, 'Duke Ellington', 'image_url_duke_ellington'),
(141, 'Dusty Springfield', 'image_url_dusty_springfield'),
(142, 'EELS', 'image_url_eels'),
(143, 'EPMD', 'image_url_epmd'),
(144, 'Eagles', 'image_url_eagles'),
(145, 'Eagles Of Death Metal', 'image_url_eagles_of_death_metal'),
(146, 'Eazy-E', 'image_url_eazy_e'),
(147, 'Eddie Cochran', 'image_url_eddie_cochran'),
(148, 'Elbow', 'image_url_elbow'),
(149, 'Ella Fitzgerald', 'image_url_ella_fitzgerald'),
(150, 'Elliott Smith', 'image_url_elliott_smith'),
(151, 'Elton John', 'image_url_elton_john'),
(152, 'Elvis Costello', 'image_url_elvis_costello'),
(153, 'Elvis Presley', 'image_url_elvis_presley'),
(154, 'Emeli Sandé', 'image_url_emeli_sande'),
(155, 'Eminem', 'image_url_eminem'),
(156, 'Enigma', 'image_url_enigma'),
(157, 'Eric B. & Rakim', 'image_url_eric_b_rakim'),
(158, 'Eric Church', 'image_url_eric_church'),
(159, 'Eric Clapton', 'image_url_eric_clapton'),
(160, 'Etta James', 'image_url_etta_james'),
(161, 'Evanescence', 'image_url_evanescence'),
(162, 'Eve', 'image_url_eve'),
(163, 'Extreme', 'image_url_extreme'),
(164, 'Fairport Convention', 'image_url_fairport_convention'),
(165, 'Fats Domino', 'image_url_fats_domino'),
(166, 'Faust', 'image_url_faust'),
(167, 'Fergie', 'image_url_fergie'),
(168, 'Fleetwood Mac', 'image_url_fleetwood_mac'),
(169, 'Florence + The Machine', 'image_url_florence_and_the_machine'),
(170, 'The Flying Burrito Brothers', 'image_url_flying_burrito_brothers'),
(171, 'Foo Fighters', 'image_url_foo_fighters'),
(172, 'Four Tops', 'image_url_four_tops'),
(173, 'Foxy Brown', 'image_url_foxy_brown'),
(174, 'Frank Sinatra', 'image_url_frank_sinatra'),
(175, 'Frank Zappa', 'image_url_frank_zappa'),
(176, 'Frankie Goes To Hollywood', 'image_url_frankie_goes_to_hollywood'),
(177, 'Freddie Mercury', 'image_url_freddie_mercury'),
(178, 'Free', 'image_url_free'),
(179, 'Frida Lyngstad', 'image_url_frida_lyngstad'),
(180, 'The Game', 'image_url_the_game'),
(181, 'Gang Starr', 'image_url_gang_starr'),
(182, 'Gary Moore', 'image_url_gary_moore'),
(183, 'Gene Krupa', 'image_url_gene_krupa'),
(184, 'Gene Vincent', 'image_url_gene_vincent'),
(185, 'Genesis', 'image_url_genesis'),
(186, 'Gentle Giant', 'image_url_gentle_giant'),
(187, 'George Benson', 'image_url_george_benson'),
(188, 'George Harrison', 'image_url_george_harrison'),
(189, 'George Michael', 'image_url_george_michael'),
(190, 'George Strait', 'image_url_george_strait'),
(191, 'George Thorogood', 'image_url_george_thorogood'),
(192, 'Georgie Fame', 'image_url_georgie_fame'),
(193, 'Ghostface Killah', 'image_url_ghostface_killah'),
(194, 'Ginger Baker', 'image_url_ginger_baker'),
(195, 'Glass Animals', 'image_url_glass_animals'),
(196, 'Glen Campbell', 'image_url_glen_campbell'),
(197, 'The Go-Go’s', 'image_url_the_go_gos'),
(198, 'Gong', 'image_url_gong'),
(199, 'Grace Jones', 'image_url_grace_jones'),
(200, 'Graham Parker', 'image_url_graham_parker'),
(201, 'Grand Funk Railroad', 'image_url_grand_funk_railroad'),
(202, 'Gregory Isaacs', 'image_url_gregory_isaacs'),
(203, 'Gregory Porter', 'image_url_gregory_porter'),
(204, 'Guns N’ Roses', 'image_url_guns_n_roses'),
(205, 'Gwen Stefani', 'image_url_gwen_stefani'),
(206, 'Halsey', 'image_url_halsey'),
(207, 'Hank Williams', 'image_url_hank_williams'),
(208, 'Heart', 'image_url_heart'),
(209, 'Heaven 17', 'image_url_heaven_17'),
(210, 'Helmet', 'image_url_helmet'),
(211, 'Herbie Hancock', 'image_url_herbie_hancock'),
(212, 'Hoobastank', 'image_url_hoobastank'),
(213, 'Howlin Wolf', 'image_url_howlin_wolf'),
(214, 'Hoyt Axton', 'image_url_hoyt_axton'),
(215, 'Huey Lewis & The News', 'image_url_huey_lewis_and_the_news'),
(216, 'The Human League', 'image_url_human_league'),
(217, 'Humble Pie', 'image_url_humble_pie'),
(218, 'INXS', 'image_url_inxs'),
(219, 'Ice Cube', 'image_url_ice_cube'),
(220, 'Iggy Pop', 'image_url_iggy_pop'),
(221, 'Imagine Dragons', 'image_url_imagine_dragons'),
(222, 'Iron Maiden', 'image_url_iron_maiden'),
(223, 'Isaac Hayes', 'image_url_isaac_hayes'),
(224, 'The Isley Brothers', 'image_url_isley_brothers'),
(225, 'It Bites', 'image_url_it_bites'),
(226, 'J.J. Cale', 'image_url_jj_cale'),
(227, 'Jack Bruce', 'image_url_jack_bruce'),
(228, 'Jack Johnson', 'image_url_jack_johnson'),
(229, 'Jackson 5', 'image_url_jackson_5'),
(230, 'Jacques Brel', 'image_url_jacques_brel'),
(231, 'Jadakiss', 'image_url_jadakiss'),
(232, 'The Jam', 'image_url_jam'),
(233, 'James', 'image_url_james'),
(234, 'James Bay', 'image_url_james_bay'),
(235, 'James Blake', 'image_url_james_blake'),
(236, 'James Brown', 'image_url_james_brown'),
(237, 'James Morrison', 'image_url_james_morrison'),
(238, 'James Taylor', 'image_url_james_taylor'),
(239, 'Jane’s Addiction', 'image_url_janes_addiction'),
(240, 'Janet Jackson', 'image_url_janet_jackson'),
(241, 'Japan & David Sylvian', 'image_url_japan_david_sylvian'),
(242, 'Jay-Z', 'image_url_jay_z'),
(243, 'Jeezy', 'image_url_jeezy'),
(244, 'Jeru the Damaja', 'image_url_jeru_the_damaja'),
(245, 'Jessie J', 'image_url_jessie_j'),
(246, 'Jimi Hendrix', 'image_url_jimi_hendrix'),
(247, 'Jimmy Buffett', 'image_url_jimmy_buffett'),
(248, 'Jimmy Cliff', 'image_url_jimmy_cliff'),
(249, 'Jimmy Eat World', 'image_url_jimmy_eat_world'),
(250, 'Jimmy Ruffin', 'image_url_jimmy_ruffin'),
(251, 'Jimmy Smith', 'image_url_jimmy_smith'),
(252, 'Joan Armatrading', 'image_url_joan_armatrading'),
(253, 'Joan Baez', 'image_url_joan_baez'),
(254, 'Joe Cocker', 'image_url_joe_cocker'),
(255, 'Joe Jackson', 'image_url_joe_jackson'),
(256, 'Joe Sample', 'image_url_joe_sample'),
(257, 'Joe Walsh / The James Gang', 'image_url_joe_walsh_james_gang'),
(258, 'John Coltrane', 'image_url_john_coltrane'),
(259, 'John Fogerty', 'image_url_john_fogerty'),
(260, 'John Lee Hooker', 'image_url_john_lee_hooker'),
(261, 'John Lennon', 'image_url_john_lennon'),
(262, 'John Martyn', 'image_url_john_martyn'),
(263, 'John Mayall', 'image_url_john_mayall'),
(264, 'John Mellencamp', 'image_url_john_mellencamp'),
(265, 'John Williams', 'image_url_john_williams'),
(266, 'Johnny Cash', 'image_url_johnny_cash'),
(267, 'Johnny Gill', 'image_url_johnny_gill'),
(268, 'Joni Mitchell', 'image_url_joni_mitchell'),
(269, 'Jonny Lang', 'image_url_jonny_lang'),
(270, 'Joss Stone', 'image_url_joss_stone'),
(271, 'Jr. Walker & The All Stars', 'image_url_jr_walker_all_stars'),
(272, 'Julie London', 'image_url_julie_london'),
(273, 'Jurassic 5', 'image_url_jurassic_5'),
(274, 'Justin Bieber', 'image_url_justin_bieber'),
(275, 'Kacey Musgraves', 'image_url_kacey_musgraves'),
(276, 'Kaiser Chiefs', 'image_url_kaiser_chiefs'),
(277, 'Kate Bush', 'image_url_kate_bush'),
(278, 'Katy Perry', 'image_url_katy_perry'),
(279, 'Keane', 'image_url_keane'),
(280, 'Keith Jarrett', 'image_url_keith_jarrett'),
(281, 'Keith Richards', 'image_url_keith_richards'),
(282, 'Keith Urban', 'image_url_keith_urban'),
(283, 'Kendrick Lamar', 'image_url_kendrick_lamar'),
(284, 'Kenny Burrell', 'image_url_kenny_burrell'),
(285, 'Kevin Coyne', 'image_url_kevin_coyne'),
(286, 'The Killers', 'image_url_killers'),
(287, 'Killing Joke', 'image_url_killing_joke'),
(288, 'Kim Carnes', 'image_url_kim_carnes'),
(289, 'The Kinks', 'image_url_kinks'),
(290, 'Kip Moore', 'image_url_kip_moore'),
(291, 'Kiss', 'image_url_kiss'),
(292, 'The Kooks', 'image_url_kooks'),
(293, 'Kool And The Gang', 'image_url_kool_and_the_gang'),
(294, 'LL Cool J', 'image_url_ll_cool_j'),
(295, 'Lady A', 'image_url_lady_a'),
(296, 'Lady GaGa', 'image_url_lady_gaga'),
(297, 'Lana Del Rey', 'image_url_lana_del_rey'),
(298, 'Laura Marling', 'image_url_laura_marling'),
(299, 'Led Zeppelin', 'image_url_led_zeppelin'),
(300, 'Lee ‘Scratch’ Perry', 'image_url_lee_scratch_perry'),
(301, 'Lenny Kravitz', 'image_url_lenny_kravitz'),
(302, 'Leon Russell', 'image_url_leon_russell'),
(303, 'Lester Young', 'image_url_lester_young'),
(304, 'Level 42', 'image_url_level_42'),
(305, 'The Libertines', 'image_url_libertines'),
(306, 'Lightnin’ Hopkins', 'image_url_lightnin_hopkins'),
(307, 'Lil Wayne', 'image_url_lil_wayne'),
(308, 'Linton Kwesi Johnson', 'image_url_linton_kwesi_johnson'),
(309, 'Lionel Richie', 'image_url_lionel_richie'),
(310, 'Little Big Town', 'image_url_little_big_town'),
(311, 'Little Richard', 'image_url_little_richard'),
(312, 'Little Steven', 'image_url_little_steven'),
(313, 'Lloyd Cole', 'image_url_lloyd_cole'),
(314, 'Lorde', 'image_url_lorde'),
(315, 'Louis Armstrong', 'image_url_louis_armstrong'),
(316, 'Lucinda Williams', 'image_url_lucinda_williams'),
(317, 'Ludacris', 'image_url_ludacris'),
(318, 'Ludovico Einaudi', 'image_url_ludovico_einaudi'),
(319, 'Luke Bryan', 'image_url_luke_bryan'),
(320, 'Lulu', 'image_url_lulu'),
(321, 'The Lumineers', 'image_url_lumineers'),
(322, 'Lynyrd Skynyrd', 'image_url_lynyrd_skynyrd'),
(323, 'Maddie & Tae', 'image_url_maddie_and_tae'),
(324, 'Madonna', 'image_url_madonna'),
(325, 'Magazine', 'image_url_magazine'),
(326, 'The Mamas & The Papas', 'image_url_mamas_and_papas'),
(327, 'Marc Almond', 'image_url_marc_almond'),
(328, 'Marilyn Manson', 'image_url_marilyn_manson'),
(329, 'Mark Knopfler', 'image_url_mark_knopfler'),
(330, 'Maroon 5', 'image_url_maroon_5'),
(331, 'Martha Reeves & The Vandellas', 'image_url_martha_reeves_vandellas'),
(332, 'The Marvelettes', 'image_url_marvelettes'),
(333, 'Marvin Gaye', 'image_url_marvin_gaye'),
(334, 'Mary Hopkin', 'image_url_mary_hopkin'),
(335, 'Mary J. Blige', 'image_url_mary_j_blige'),
(336, 'Mary Wells', 'image_url_mary_wells'),
(337, 'Massive Attack', 'image_url_massive_attack'),
(338, 'Master P', 'image_url_master_p'),
(339, 'The Mavericks', 'image_url_mavericks'),
(340, 'Maxi Priest', 'image_url_maxi_priest'),
(341, 'McCoy Tyner', 'image_url_mccoy_tyner'),
(342, 'Meat Loaf', 'image_url_meat_loaf'),
(343, 'Megadeth', 'image_url_megadeth'),
(344, 'Melody Gardot', 'image_url_melody_gardot'),
(345, 'Metallica', 'image_url_metallica'),
(346, 'Method Man', 'image_url_method_man'),
(347, 'Michael Jackson', 'image_url_michael_jackson'),
(348, 'Michael Kiwanuka', 'image_url_michael_kiwanuka'),
(349, 'Michael Nyman', 'image_url_michael_nyman'),
(350, 'Mike & the Mechanics', 'image_url_mike_and_the_mechanics'),
(351, 'Mike Oldfield', 'image_url_mike_oldfield'),
(352, 'Miles Davis', 'image_url_miles_davis'),
(353, 'Minnie Riperton', 'image_url_minnie_riperton'),
(354, 'The Moody Blues', 'image_url_moody_blues'),
(355, 'Morrissey', 'image_url_morrissey'),
(356, 'Motörhead', 'image_url_motorhead'),
(357, 'Muddy Waters', 'image_url_muddy_waters'),
(358, 'Mumford & Sons', 'image_url_mumford_and_sons'),
(359, 'Mötley Crüe', 'image_url_motley_crue'),
(360, 'N.W.A', 'image_url_nwa'),
(361, 'Nanci Griffith', 'image_url_nanci_griffith'),
(362, 'Nas', 'image_url_nas'),
(363, 'Nat King Cole', 'image_url_nat_king_cole'),
(364, 'Nazareth', 'image_url_nazareth'),
(365, 'Ne-Yo', 'image_url_ne_yo'),
(366, 'Neil Diamond', 'image_url_neil_diamond'),
(367, 'Neil Young', 'image_url_neil_young'),
(368, 'Nelly', 'image_url_nelly'),
(369, 'Neneh Cherry', 'image_url_neneh_cherry'),
(370, 'New Edition', 'image_url_new_edition'),
(371, 'New York Dolls', 'image_url_new_york_dolls'),
(372, 'Nick Drake', 'image_url_nick_drake'),
(373, 'Nicki Minaj', 'image_url_nicki_minaj'),
(374, 'Nik Kershaw', 'image_url_nik_kershaw'),
(375, 'Nina Simone', 'image_url_nina_simone'),
(376, 'Nine Inch Nails', 'image_url_nine_inch_nails'),
(377, 'Nirvana', 'image_url_nirvana'),
(378, 'The Nitty Gritty Dirt Band', 'image_url_nitty_gritty_dirt_band'),
(379, 'No Doubt', 'image_url_no_doubt'),
(380, 'Norah Jones', 'image_url_norah_jones'),
(381, 'OMD', 'image_url_omd'),
(382, 'Ocean Colour Scene', 'image_url_ocean_colour_scene'),
(383, 'OneRepublic', 'image_url_onerepublic'),
(384, 'Onyx', 'image_url_onyx'),
(385, 'Oscar Peterson', 'image_url_oscar_peterson'),
(386, 'Otis Redding', 'image_url_otis_redding'),
(387, 'The Ozark Mountain Daredevils', 'image_url_ozark_mountain_daredevils'),
(388, 'PJ Harvey', 'image_url_pj_harvey'),
(389, 'Papa Roach', 'image_url_papa_roach'),
(390, 'Pat Benatar', 'image_url_pat_benatar'),
(391, 'Pato Banton', 'image_url_pato_banton'),
(392, 'Patsy Cline', 'image_url_patsy_cline'),
(393, 'Patty Griffin', 'image_url_patty_griffin'),
(394, 'Paul McCartney and Wings', 'image_url_paul_mccartney_and_wings'),
(395, 'Paul Simon', 'image_url_paul_simon'),
(396, 'Paul Weller', 'image_url_paul_weller'),
(397, 'Peaches & Herb', 'image_url_peaches_and_herb'),
(398, 'Pearl Jam', 'image_url_pearl_jam'),
(399, 'Peggy Lee', 'image_url_peggy_lee'),
(400, 'Pete Townshend', 'image_url_pete_townshend'),
(401, 'Peter Frampton', 'image_url_peter_frampton'),
(402, 'Phil Collins', 'image_url_phil_collins'),
(403, 'Phil Manzanera', 'image_url_phil_manzanera'),
(404, 'PiL (Public Image Ltd)', 'image_url_public_image_ltd'),
(405, 'Pink Floyd', 'image_url_pink_floyd'),
(406, 'Placebo', 'image_url_placebo'),
(407, 'Poco', 'image_url_poco'),
(408, 'Poison', 'image_url_poison'),
(409, 'The Police', 'image_url_police'),
(410, 'Portishead', 'image_url_portishead'),
(411, 'Prince', 'image_url_prince'),
(412, 'Public Enemy', 'image_url_public_enemy'),
(413, 'Pulp', 'image_url_pulp'),
(414, 'Queen', 'image_url_queen'),
(415, 'Queens Of The Stone Age', 'image_url_queens_of_the_stone_age'),
(416, 'Quicksilver Messenger Service', 'image_url_quicksilver_messenger_service'),
(417, 'Quincy Jones', 'image_url_quincy_jones'),
(418, 'R.E.M.', 'image_url_rem'),
(419, 'Rainbow', 'image_url_rainbow'),
(420, 'Rammstein', 'image_url_rammstein'),
(421, 'Ray Charles', 'image_url_ray_charles'),
(422, 'Reba McEntire', 'image_url_reba_mcentire'),
(423, 'Red Hot Chili Peppers', 'image_url_red_hot_chili_peppers'),
(424, 'Redman', 'image_url_redman'),
(425, 'Richie Havens', 'image_url_richie_havens'),
(426, 'Rick James', 'image_url_rick_james'),
(427, 'Rick Nelson', 'image_url_rick_nelson'),
(428, 'Rick Ross', 'image_url_rick_ross'),
(429, 'Rick Wakeman', 'image_url_rick_wakeman'),
(430, 'The Righteous Brothers', 'image_url_righteous_brothers'),
(431, 'Rihanna', 'image_url_rihanna'),
(432, 'Ringo Starr', 'image_url_ringo_starr'),
(433, 'Rise Against', 'image_url_rise_against'),
(434, 'Rob Zombie', 'image_url_rob_zombie'),
(435, 'Robbie Williams', 'image_url_robbie_williams'),
(436, 'Robert Cray', 'image_url_robert_cray'),
(437, 'Robert Glasper', 'image_url_robert_glasper'),
(438, 'Robert Palmer', 'image_url_robert_palmer'),
(439, 'Robert Plant', 'image_url_robert_plant'),
(440, 'Rod Stewart', 'image_url_rod_stewart'),
(441, 'Roger Daltrey', 'image_url_roger_daltrey'),
(442, 'The Rolling Stones', 'image_url_rolling_stones'),
(443, 'Ronnie Lane', 'image_url_ronnie_lane'),
(444, 'Ronnie Wood', 'image_url_ronnie_wood'),
(445, 'Rory Gallagher', 'image_url_rory_gallagher'),
(446, 'The Roots', 'image_url_roots'),
(447, 'Rosanne Cash', 'image_url_rosanne_cash'),
(448, 'Roxy Music', 'image_url_roxy_music'),
(449, 'Roy Orbison', 'image_url_roy_orbison'),
(450, 'Ruff Ryders', 'image_url_ruff_ryders'),
(451, 'Rufus Wainwright', 'image_url_rufus_wainwright'),
(452, 'Rush', 'image_url_rush'),
(453, 'The Ruts', 'image_url_ruts'),
(454, 'Saint Etienne', 'image_url_saint_etienne'),
(455, 'Salt-n-Pepa', 'image_url_salt_n_pepa'),
(456, 'Sam Cooke', 'image_url_sam_cooke'),
(457, 'Sam Hunt', 'image_url_sam_hunt'),
(458, 'Sam Smith', 'image_url_sam_smith'),
(459, 'Sammy Hagar', 'image_url_sammy_hagar'),
(460, 'Sandy Denny', 'image_url_sandy_denny'),
(461, 'Schiller', 'image_url_schiller'),
(462, 'Scorpions', 'image_url_scorpions'),
(463, 'Scott Walker', 'image_url_scott_walker'),
(464, 'Secret Garden', 'image_url_secret_garden'),
(465, 'Selena Gomez', 'image_url_selena_gomez'),
(466, 'Sensational Alex Harvey Band', 'image_url_sensational_alex_harvey_band'),
(467, 'Serge Gainsbourg', 'image_url_serge_gainsbourg'),
(468, 'Sergio Mendes', 'image_url_sergio_mendes'),
(469, 'Sex Pistols', 'image_url_sex_pistols'),
(470, 'Shaggy', 'image_url_shaggy'),
(471, 'Sham 69', 'image_url_sham_69'),
(472, 'Shania Twain', 'image_url_shania_twain'),
(473, 'Sheryl Crow', 'image_url_sheryl_crow'),
(474, 'Simple Minds', 'image_url_simple_minds'),
(475, 'Siouxsie & The Banshees', 'image_url_siouxsie_and_the_banshees'),
(476, 'Slayer', 'image_url_slayer'),
(477, 'Slick Rick', 'image_url_slick_rick'),
(478, 'Sly & Robbie', 'image_url_sly_and_robbie'),
(479, 'Small Faces', 'image_url_small_faces'),
(480, 'The Smashing Pumpkins', 'image_url_smashing_pumpkins'),
(481, 'Smokey Robinson', 'image_url_smokey_robinson'),
(482, 'Smokey Robinson & The Miracles', 'image_url_smokey_robinson_miracles'),
(483, 'Snoop Dogg', 'image_url_snoop_dogg'),
(484, 'Snow Patrol', 'image_url_snow_patrol'),
(485, 'Soft Cell', 'image_url_soft_cell'),
(486, 'Sonic Youth', 'image_url_sonic_youth'),
(487, 'Sonny Boy Williamson', 'image_url_sonny_boy_williamson'),
(488, 'Soul II Soul', 'image_url_soul_ii_soul'),
(489, 'Soundgarden', 'image_url_soundgarden'),
(490, 'Spandau Ballet', 'image_url_spandau_ballet'),
(491, 'Sparks', 'image_url_sparks'),
(492, 'Spice Girls', 'image_url_spice_girls'),
(493, 'Stan Getz', 'image_url_stan_getz'),
(494, 'Stan Kenton', 'image_url_stan_kenton'),
(495, 'Stanley Clarke', 'image_url_stanley_clarke'),
(496, 'Status Quo', 'image_url_status_quo'),
(497, 'Stealers Wheel', 'image_url_stealers_wheel'),
(498, 'Steam', 'image_url_steam'),
(499, 'Steel Pulse', 'image_url_steel_pulse'),
(500, 'Steve Earle', 'image_url_steve_earle'),
(501, 'Steve Hackett', 'image_url_steve_hackett'),
(502, 'Steve Harley & Cockney Rebel', 'image_url_steve_harley_cockney_rebel'),
(503, 'Steve Hillage', 'image_url_steve_hillage'),
(504, 'Steve Miller Band', 'image_url_steve_miller_band'),
(505, 'Steve Winwood', 'image_url_steve_winwood'),
(506, 'Stevie Nicks', 'image_url_stevie_nicks'),
(507, 'Stevie Ray Vaughan', 'image_url_stevie_ray_vaughan'),
(508, 'Stevie Wonder', 'image_url_stevie_wonder'),
(509, 'Sting', 'image_url_sting'),
(510, 'Stone Roses', 'image_url_stone_roses'),
(511, 'The Stone Roses', 'image_url_stone_roses'),
(512, 'Stray Cats', 'image_url_stray_cats'),
(513, 'Styx', 'image_url_styx'),
(514, 'Sufjan Stevens', 'image_url_sufjan_stevens'),
(515, 'The Sugarcubes', 'image_url_sugarcubes'),
(516, 'Supertramp', 'image_url_supertramp'),
(517, 'The Supremes', 'image_url_supremes'),
(518, 'Suzanne Vega', 'image_url_suzanne_vega'),
(519, 'Swans', 'image_url_swans'),
(520, 'The Sweet', 'image_url_sweet'),
(521, 'Swing Out Sister', 'image_url_swing_out_sister'),
(522, 'Syd Barrett', 'image_url_syd_barrett'),
(523, 'System Of A Down', 'image_url_system_of_a_down'),
(524, 'T. Rex', 'image_url_t_rex'),
(525, 'TLC', 'image_url_tlc'),
(526, 'TV On The Radio', 'image_url_tv_on_the_radio'),
(527, 'Talking Heads', 'image_url_talking_heads'),
(528, 'Tammy Wynette', 'image_url_tammy_wynette'),
(529, 'Tangerine Dream', 'image_url_tangerine_dream'),
(530, 'Taylor Swift', 'image_url_taylor_swift'),
(531, 'Tears For Fears', 'image_url_tears_for_fears'),
(532, 'Ted Nugent', 'image_url_ted_nugent'),
(533, 'The Temptations', 'image_url_temptations'),
(534, 'Terence Trent D’Arby', 'image_url_terence_trent_darby'),
(535, 'The The', 'image_url_the_the'),
(536, 'Thelonious Monk', 'image_url_thelonious_monk'),
(537, 'They Might Be Giants', 'image_url_they_might_be_giants'),
(538, 'Thin Lizzy', 'image_url_thin_lizzy'),
(539, 'Thomas Dolby', 'image_url_thomas_dolby'),
(540, 'Tim Buckley', 'image_url_tim_buckley'),
(541, 'Tim Hardin', 'image_url_tim_hardin'),
(542, 'Timbaland', 'image_url_timbaland'),
(543, 'Tina Turner', 'image_url_tina_turner'),
(544, 'Tito Puente', 'image_url_tito_puente'),
(545, 'Toad the Wet Sprocket', 'image_url_toad_the_wet_sprocket'),
(546, 'Tom Jones', 'image_url_tom_jones'),
(547, 'Tom Petty', 'image_url_tom_petty'),
(548, 'Tom Waits', 'image_url_tom_waits'),
(549, 'Tommy James & The Shondells', 'image_url_tommy_james_shondells'),
(550, 'Toni Braxton', 'image_url_toni_braxton'),
(551, 'Tori Amos', 'image_url_tori_amos'),
(552, 'Toto', 'image_url_toto'),
(553, 'The Troggs', 'image_url_troggs'),
(554, 'U2', 'image_url_u2'),
(555, 'UB40', 'image_url_ub40'),
(556, 'Ultravox', 'image_url_ultravox'),
(557, 'Underworld', 'image_url_underworld'),
(558, 'The Undertones', 'image_url_undertones'),
(559, 'Unkle', 'image_url_unkle'),
(560, 'Uriah Heep', 'image_url_uriah_heep'),
(561, 'Usher', 'image_url_usher'),
(562, 'Van Halen', 'image_url_van_halen'),
(563, 'Van Morrison', 'image_url_van_morrison'),
(564, 'Vanessa Williams', 'image_url_vanessa_williams'),
(565, 'Vangelis', 'image_url_vangelis'),
(566, 'The Vapors', 'image_url_vapors'),
(567, 'The Velvet Underground', 'image_url_velvet_underground'),
(568, 'The Ventures', 'image_url_ventures'),
(569, 'Vera Lynn', 'image_url_vera_lynn'),
(570, 'Vic Chesnutt', 'image_url_vic_chesnutt'),
(571, 'Vince Guaraldi', 'image_url_vince_guaraldi'),
(572, 'Violent Femmes', 'image_url_violent_femmes'),
(573, 'Visage', 'image_url_visage'),
(574, 'Wang Chung', 'image_url_wang_chung'),
(575, 'Warpaint', 'image_url_warpaint'),
(576, 'Warren Zevon', 'image_url_warren_zevon'),
(577, 'The Waterboys', 'image_url_waterboys'),
(578, 'The Watson Twins', 'image_url_watson_twins'),
(579, 'The Weeknd', 'image_url_weeknd'),
(580, 'Ween', 'image_url_ween'),
(581, 'Weezer', 'image_url_weezer'),
(582, 'Wendy Carlos', 'image_url_wendy_carlos'),
(583, 'Wet Wet Wet', 'image_url_wet_wet_wet'),
(584, 'The White Stripes', 'image_url_white_stripes'),
(585, 'Whitney Houston', 'image_url_whitney_houston'),
(586, 'The Who', 'image_url_who'),
(587, 'Wilco', 'image_url_wilco'),
(588, 'Willie Nelson', 'image_url_willie_nelson'),
(589, 'Wilson Pickett', 'image_url_wilson_pickett'),
(590, 'Wings', 'image_url_wings'),
(591, 'The Wombats', 'image_url_wombats'),
(592, 'The Wurzels', 'image_url_wurzels'),
(593, 'X', 'image_url_x'),
(594, 'XTC', 'image_url_xtc'),
(595, 'The xx', 'image_url_xx'),
(596, 'Yazoo', 'image_url_yazoo'),
(597, 'Yes', 'image_url_yes'),
(598, 'Yo La Tengo', 'image_url_yo_la_tengo'),
(599, 'Yoko Ono', 'image_url_yoko_ono'),
(600, 'The Youngbloods', 'image_url_youngbloods'),
(601, 'The Young Rascals', 'image_url_young_rascals'),
(602, 'The Zombies', 'image_url_zombies'),
(603, 'ZZ Top', 'image_url_zz_top');
COMMIT;


-- -----------------------------------------------------
-- Data for table `song`
-- -----------------------------------------------------
START TRANSACTION;
USE `artiststrackerdb`;
INSERT INTO `song` (`id`, `name`, `song_length`, `genre`, `album_title`, `artist_id`) VALUES (1, 'S.O.S.', 3.22, 'Disco', 'Arrival', 6),
(2, 'Mamma Mia', 3.32, 'Pop', 'ABBA', 6),
(3, 'Waterloo', 2.42, 'Pop', 'Waterloo', 6),
(4, 'I Do, I Do, I Do, I Do, I Do', 3.17, 'Pop', 'ABBA', 6),
(5, 'Dancing Queen', 3.51, 'Disco', 'Arrival', 6);

COMMIT;

