-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema artiststrackerdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `artiststrackerdb` ;

-- -----------------------------------------------------
-- Schema artiststrackerdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `artiststrackerdb` DEFAULT CHARACTER SET utf8 ;
USE `artiststrackerdb` ;

-- -----------------------------------------------------
-- Table `artist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `artist` ;

CREATE TABLE IF NOT EXISTS `artist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `image` VARCHAR(500) NULL DEFAULT 'default',
  `band` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `song`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `song` ;

CREATE TABLE IF NOT EXISTS `song` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `song_length` DOUBLE NULL,
  `release_year` INT NULL,
  `genre` VARCHAR(45) NULL,
  `album_title` VARCHAR(100) NULL,
  `artist_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_song_artist_idx` (`artist_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_song_artist`
    FOREIGN KEY (`artist_id`)
    REFERENCES `artist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS artistsuser@localhost;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'artistsuser'@'localhost' IDENTIFIED BY 'artistsuser';

GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE * TO 'artistsuser'@'localhost';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `artist`
-- -----------------------------------------------------
START TRANSACTION;
USE `artiststrackerdb`;
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (1, '2Pac', 'image_url_2pac');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (2, 'A', 'image_url_a');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (3, 'Adele', 'image_url_adele');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (4, 'Aerosmith', 'image_url_aerosmith');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (5, 'Alabama Shakes', 'image_url_alabama_shakes');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (6, 'Alan Jackson', 'image_url_alan_jackson');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (7, 'Albert King', 'image_url_albert_king');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (8, 'Alice Cooper', 'image_url_alice_cooper');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (9, 'Alison Krauss', 'image_url_alison_krauss');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (10, 'Amy Winehouse', 'image_url_amy_winehouse');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (11, 'Andre Rieu', 'image_url_andre_rieu');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (12, 'Andrea Bocelli', 'image_url_andrea_bocelli');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (13, 'Andrew W.K.', 'image_url_andrew_w_k_');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (14, 'Anthrax', 'image_url_anthrax');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (15, 'Antonio Carlos Jobim', 'image_url_antonio_carlos_jobim');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (16, 'Apache Indian', 'image_url_apache_indian');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (17, 'Arcade Fire', 'image_url_arcade_fire');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (18, 'Arctic Monkeys', 'image_url_arctic_monkeys');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (19, 'Ariana Grande', 'image_url_ariana_grande');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (20, 'Arrested Development', 'image_url_arrested_development');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (21, 'Ashley Campbell', 'image_url_ashley_campbell');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (22, 'Aswad', 'image_url_aswad');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (23, 'Atlanta Rhythm Section', 'image_url_atlanta_rhythm_section');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (24, 'Audioslave', 'image_url_audioslave');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (25, 'Avril Lavigne', 'image_url_avril_lavigne');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (26, 'B.B. King', 'image_url_b_b__king');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (27, 'Backstreet Boys', 'image_url_backstreet_boys');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (28, 'Badfinger', 'image_url_badfinger');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (29, 'Barclay James Harvest', 'image_url_barclay_james_harvest');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (30, 'Barry White', 'image_url_barry_white');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (31, 'The Beach Boys', 'image_url_the_beach_boys');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (32, 'The Beatles', 'image_url_the_beatles');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (33, 'Beck', 'image_url_beck');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (34, 'Bee Gees', 'image_url_bee_gees');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (35, 'Belinda Carlisle', 'image_url_belinda_carlisle');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (36, 'Ben Harper', 'image_url_ben_harper');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (37, 'Ben Howard', 'image_url_ben_howard');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (38, 'Benny Andersson', 'image_url_benny_andersson');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (39, 'Beyoncé', 'image_url_beyoncé');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (40, 'Big Country', 'image_url_big_country');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (41, 'Big Star', 'image_url_big_star');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (42, 'Bill Evans', 'image_url_bill_evans');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (43, 'Billie Eilish', 'image_url_billie_eilish');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (44, 'Billie Holiday', 'image_url_billie_holiday');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (45, 'Billy Currington', 'image_url_billy_currington');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (46, 'Billy Fury', 'image_url_billy_fury');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (47, 'Billy Preston', 'image_url_billy_preston');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (48, 'Björk', 'image_url_björk');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (49, 'Black Eyed Peas', 'image_url_black_eyed_peas');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (50, 'Black Sabbath', 'image_url_black_sabbath');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (51, 'Black Uhuru', 'image_url_black_uhuru');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (52, 'Blind Faith', 'image_url_blind_faith');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (53, 'Blink-182', 'image_url_blink-182');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (54, 'Blondie', 'image_url_blondie');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (55, 'Blue Cheer', 'image_url_blue_cheer');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (56, 'Bo Diddley', 'image_url_bo_diddley');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (57, 'Bob Dylan', 'image_url_bob_dylan');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (58, 'Bob Marley', 'image_url_bob_marley');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (59, 'Bob Seger', 'image_url_bob_seger');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (60, 'Bon Jovi', 'image_url_bon_jovi');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (61, 'Bonnie Raitt', 'image_url_bonnie_raitt');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (62, 'Booker T', 'image_url_booker_t');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (63, 'Boyz II Men', 'image_url_boyz_ii_men');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (64, 'Brantley Gilbert', 'image_url_brantley_gilbert');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (65, 'Brenda Holloway', 'image_url_brenda_holloway');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (66, 'Brian Eno', 'image_url_brian_eno');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (67, 'The Brothers Johnson', 'image_url_the_brothers_johnson');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (68, 'Bruce Springsteen', 'image_url_bruce_springsteen');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (69, 'Bruno Mars', 'image_url_bruno_mars');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (70, 'Bryan Adams', 'image_url_bryan_adams');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (71, 'Bryan Ferry', 'image_url_bryan_ferry');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (72, 'Buddy Guy', 'image_url_buddy_guy');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (73, 'Buddy Holly', 'image_url_buddy_holly');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (74, 'Burning Spear', 'image_url_burning_spear');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (75, 'Burt Bacharach', 'image_url_burt_bacharach');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (76, 'The Cadillac Three', 'image_url_the_cadillac_three');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (77, 'Camel', 'image_url_camel');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (78, 'Canned Heat', 'image_url_canned_heat');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (79, 'Captain Beefheart', 'image_url_captain_beefheart');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (80, 'Caravan', 'image_url_caravan');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (81, 'Carpenters', 'image_url_carpenters');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (82, 'Carrie Underwood', 'image_url_carrie_underwood');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (83, 'Cat Stevens', 'image_url_cat_stevens');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (84, 'Cher', 'image_url_cher');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (85, 'Chic', 'image_url_chic');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (86, 'Chicago', 'image_url_chicago');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (87, 'Chicane', 'image_url_chicane');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (88, 'Chris Brown', 'image_url_chris_brown');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (89, 'Chris Cornell', 'image_url_chris_cornell');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (90, 'Chris Stapleton', 'image_url_chris_stapleton');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (91, 'Chuck Berry', 'image_url_chuck_berry');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (92, 'Cinderella', 'image_url_cinderella');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (93, 'The Clash', 'image_url_the_clash');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (94, 'Climax Blues Band', 'image_url_climax_blues_band');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (95, 'Coleman Hawkins', 'image_url_coleman_hawkins');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (96, 'Commodores', 'image_url_commodores');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (97, 'Common', 'image_url_common');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (98, 'The Common Linnets', 'image_url_the_common_linnets');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (99, 'Corinne Bailey Rae', 'image_url_corinne_bailey_rae');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (100, 'Count Basie', 'image_url_count_basie');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (101, 'Counting Crows', 'image_url_counting_crows');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (102, 'Craig Armstrong', 'image_url_craig_armstrong');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (103, 'The Cranberries', 'image_url_the_cranberries');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (104, 'Cream', 'image_url_cream');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (105, 'Creedence Clearwater Revival', 'image_url_creedence_clearwater_revival');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (106, 'Crowded House', 'image_url_crowded_house');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (107, 'Culture Club', 'image_url_culture_club');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (108, 'The Cure', 'image_url_the_cure');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (109, 'Cutting Crew', 'image_url_cutting_crew');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (110, 'Cyndi Lauper', 'image_url_cyndi_lauper');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (111, 'D Angelo', 'image_url_d_angelo');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (112, 'DMX', 'image_url_dmx');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (113, 'Daft Punk', 'image_url_daft_punk');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (114, 'The Damned', 'image_url_the_damned');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (115, 'Daniel Hope', 'image_url_daniel_hope');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (116, 'Danny Wilson & Gary Clark', 'image_url_danny_wilson_&_gary_clark');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (117, 'David Bowie', 'image_url_david_bowie');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (118, 'Dean Martin', 'image_url_dean_martin');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (119, 'Debarge', 'image_url_debarge');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (120, 'Deep Purple', 'image_url_deep_purple');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (121, 'Def Leppard', 'image_url_def_leppard');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (122, 'Demi Lovato', 'image_url_demi_lovato');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (123, 'Demis Roussos', 'image_url_demis_roussos');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (124, 'Derek And The Dominos', 'image_url_derek_and_the_dominos');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (125, 'Desmond Dekker', 'image_url_desmond_dekker');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (126, 'Diana Krall', 'image_url_diana_krall');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (127, 'Diana Ross', 'image_url_diana_ross');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (128, 'Diana Ross & The Supremes', 'image_url_diana_ross_&_the_supremes');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (129, 'Dierks Bentley', 'image_url_dierks_bentley');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (130, 'Dinah Washington', 'image_url_dinah_washington');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (131, 'Dio', 'image_url_dio');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (132, 'Dire Straits', 'image_url_dire_straits');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (133, 'Disclosure', 'image_url_disclosure');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (134, 'Dolly Parton', 'image_url_dolly_parton');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (135, 'Don Henley', 'image_url_don_henley');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (136, 'Donna Summer', 'image_url_donna_summer');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (137, 'The Doors', 'image_url_the_doors');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (138, 'Dr Dre', 'image_url_dr_dre');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (139, 'Drake', 'image_url_drake');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (140, 'Duke Ellington', 'image_url_duke_ellington');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (141, 'Duran Duran', 'image_url_duran_duran');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (142, 'Dusty Springfield', 'image_url_dusty_springfield');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (143, 'EELS', 'image_url_eels');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (144, 'EPMD', 'image_url_epmd');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (145, 'Eagles', 'image_url_eagles');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (146, 'Eagles Of Death Metal', 'image_url_eagles_of_death_metal');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (147, 'Eazy-E', 'image_url_eazy-e');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (148, 'Ed Sheeran', 'image_url_ed_sheeran');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (149, 'Eddie Cochran', 'image_url_eddie_cochran');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (150, 'Edith Piaf', 'image_url_edith_piaf');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (151, 'Elbow', 'image_url_elbow');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (152, 'Ella Fitzgerald', 'image_url_ella_fitzgerald');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (153, 'Ellie Goulding', 'image_url_ellie_goulding');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (154, 'Elliott Smith', 'image_url_elliott_smith');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (155, 'Elton John', 'image_url_elton_john');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (156, 'Elvis Costello', 'image_url_elvis_costello');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (157, 'Elvis Presley', 'image_url_elvis_presley');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (158, 'Emeli Sandé', 'image_url_emeli_sandé');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (159, 'Eminem', 'image_url_eminem');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (160, 'Enigma', 'image_url_enigma');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (161, 'Ennio Morricone', 'image_url_ennio_morricone');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (162, 'Enya', 'image_url_enya');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (163, 'Eric B. & Rakim', 'image_url_eric_b__&_rakim');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (164, 'Eric Church', 'image_url_eric_church');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (165, 'Eric Clapton', 'image_url_eric_clapton');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (166, 'Ernest Tubb', 'image_url_ernest_tubb');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (167, 'Eurythmics', 'image_url_eurythmics');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (168, 'Eva Cassidy', 'image_url_eva_cassidy');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (169, 'Evanescence', 'image_url_evanescence');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (170, 'Everly Brothers', 'image_url_everly_brothers');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (171, 'Everything Everything', 'image_url_everything_everything');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (172, 'The Faces', 'image_url_the_faces');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (173, 'Fairport Convention', 'image_url_fairport_convention');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (174, 'Faith Evans', 'image_url_faith_evans');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (175, 'Faith Hill', 'image_url_faith_hill');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (176, 'Faith No More', 'image_url_faith_no_more');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (177, 'Fall Out Boy', 'image_url_fall_out_boy');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (178, 'Fatboy Slim', 'image_url_fatboy_slim');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (179, 'Fats Domino', 'image_url_fats_domino');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (180, 'Feist', 'image_url_feist');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (181, 'Fela Kuti', 'image_url_fela_kuti');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (182, 'Fergie', 'image_url_fergie');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (183, 'Fiona Apple', 'image_url_fiona_apple');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (184, 'Fleetwood Mac', 'image_url_fleetwood_mac');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (185, 'Foo Fighters', 'image_url_foo_fighters');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (186, 'Foreigner', 'image_url_foreigner');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (187, 'Four Tops', 'image_url_four_tops');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (188, 'The Four Seasons', 'image_url_the_four_seasons');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (189, 'The Four Tops', 'image_url_the_four_tops');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (190, 'Frank Ocean', 'image_url_frank_ocean');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (191, 'Frank Sinatra', 'image_url_frank_sinatra');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (192, 'Frank Turner', 'image_url_frank_turner');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (193, 'Franz Ferdinand', 'image_url_franz_ferdinand');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (194, 'Freddie Hubbard', 'image_url_freddie_hubbard');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (195, 'Free', 'image_url_free');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (196, 'Fugees', 'image_url_fugees');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (197, 'Fun.', 'image_url_fun_');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (198, 'Future Islands', 'image_url_future_islands');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (199, 'The Game', 'image_url_the_game');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (200, 'Gang Starr', 'image_url_gang_starr');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (201, 'Garbage', 'image_url_garbage');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (202, 'Gareth Gates', 'image_url_gareth_gates');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (203, 'Gary Moore', 'image_url_gary_moore');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (204, 'Gary Numan', 'image_url_gary_numan');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (205, 'Genesis', 'image_url_genesis');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (206, 'George Benson', 'image_url_george_benson');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (207, 'George Harrison', 'image_url_george_harrison');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (208, 'George Michael', 'image_url_george_michael');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (209, 'George Strait', 'image_url_george_strait');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (210, 'Gerry Rafferty', 'image_url_gerry_rafferty');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (211, 'Gibson Brothers', 'image_url_gibson_brothers');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (212, 'Gil Scott-Heron', 'image_url_gil_scott-heron');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (213, 'Glen Campbell', 'image_url_glen_campbell');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (214, 'Glen Hansard & Marketa Irglova', 'image_url_glen_hansard_&_marketa_irglova');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (215, 'Glenn Miller', 'image_url_glenn_miller');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (216, 'Gloria Gaynor', 'image_url_gloria_gaynor');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (217, 'Gnarls Barkley', 'image_url_gnarls_barkley');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (218, 'Godsmack', 'image_url_godsmack');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (219, 'Gordon Lightfoot', 'image_url_gordon_lightfoot');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (220, 'Grace Jones', 'image_url_grace_jones');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (221, 'Grace VanderWaal', 'image_url_grace_vanderwaal');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (222, 'Grandmaster Flash & The Furious Five', 'image_url_grandmaster_flash_&_the_furious_five');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (223, 'The Grateful Dead', 'image_url_the_grateful_dead');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (224, 'Green Day', 'image_url_green_day');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (225, 'Gregory Isaacs', 'image_url_gregory_isaacs');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (226, 'The Guess Who', 'image_url_the_guess_who');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (227, 'Guns N Roses', 'image_url_guns_n_roses');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (228, 'Guru', 'image_url_guru');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (229, 'Gwen Stefani', 'image_url_gwen_stefani');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (230, 'HIM', 'image_url_him');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (231, 'Halsey', 'image_url_halsey');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (232, 'Hank Williams', 'image_url_hank_williams');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (233, 'Hank Williams Jr', 'image_url_hank_williams_jr');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (234, 'Hank Williams, Jr.', 'image_url_hank_williams__jr_');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (235, 'Hans Zimmer', 'image_url_hans_zimmer');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (236, 'Hanson', 'image_url_hanson');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (237, 'Harry Nilsson', 'image_url_harry_nilsson');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (238, 'Harry Styles', 'image_url_harry_styles');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (239, 'Heart', 'image_url_heart');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (240, 'Heaven 17', 'image_url_heaven_17');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (241, 'The Heavy', 'image_url_the_heavy');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (242, 'Herbie Hancock', 'image_url_herbie_hancock');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (243, 'Holly Valance', 'image_url_holly_valance');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (244, 'The Hollies', 'image_url_the_hollies');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (245, 'Hootie & The Blowfish', 'image_url_hootie_&_the_blowfish');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (246, 'Howlin Wolf', 'image_url_howlin_wolf');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (247, 'Hozier', 'image_url_hozier');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (248, 'Huey Lewis & The News', 'image_url_huey_lewis_&_the_news');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (249, 'Hugh Laurie', 'image_url_hugh_laurie');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (250, 'Human League', 'image_url_human_league');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (251, 'Humble Pie', 'image_url_humble_pie');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (252, 'Ice Cube', 'image_url_ice_cube');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (253, 'Iggy Pop', 'image_url_iggy_pop');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (254, 'Imagine Dragons', 'image_url_imagine_dragons');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (255, 'Incubus', 'image_url_incubus');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (256, 'Indigo Girls', 'image_url_indigo_girls');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (257, 'INXS', 'image_url_inxs');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (258, 'Iron Maiden', 'image_url_iron_maiden');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (259, 'Isaac Hayes', 'image_url_isaac_hayes');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (260, 'J Dilla', 'image_url_j_dilla');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (261, 'JJ Cale', 'image_url_jj_cale');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (262, 'Jack Johnson', 'image_url_jack_johnson');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (263, 'Jack White', 'image_url_jack_white');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (264, 'Jackson Browne', 'image_url_jackson_browne');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (265, 'Jacques Brel', 'image_url_jacques_brel');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (266, 'James Blunt', 'image_url_james_blunt');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (267, 'James Brown', 'image_url_james_brown');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (268, 'James Taylor', 'image_url_james_taylor');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (269, 'Janet Jackson', 'image_url_janet_jackson');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (270, 'Janis Joplin', 'image_url_janis_joplin');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (271, 'Jason Aldean', 'image_url_jason_aldean');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (272, 'Jason Derulo', 'image_url_jason_derulo');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (273, 'Jay Z', 'image_url_jay_z');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (274, 'Jeff Beck', 'image_url_jeff_beck');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (275, 'Jeff Buckley', 'image_url_jeff_buckley');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (276, 'Jeff Lynne', 'image_url_jeff_lynne');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (277, 'Jeff Wayne', 'image_url_jeff_wayne');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (278, 'Jennifer Lopez', 'image_url_jennifer_lopez');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (279, 'Jerry Garcia', 'image_url_jerry_garcia');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (280, 'Jerry Lee Lewis', 'image_url_jerry_lee_lewis');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (281, 'Jethro Tull', 'image_url_jethro_tull');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (282, 'Jimi Hendrix', 'image_url_jimi_hendrix');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (283, 'Jimmy Cliff', 'image_url_jimmy_cliff');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (284, 'Jimmy Eat World', 'image_url_jimmy_eat_world');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (285, 'Jimmy Smith', 'image_url_jimmy_smith');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (286, 'Joan Baez', 'image_url_joan_baez');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (287, 'Joe Bonamassa', 'image_url_joe_bonamassa');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (288, 'Joe Cocker', 'image_url_joe_cocker');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (289, 'Joe Satriani', 'image_url_joe_satriani');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (290, 'Joe Walsh', 'image_url_joe_walsh');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (291, 'John Coltrane', 'image_url_john_coltrane');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (292, 'John Denver', 'image_url_john_denver');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (293, 'John Fahey', 'image_url_john_fahey');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (294, 'John Lee Hooker', 'image_url_john_lee_hooker');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (295, 'John Legend', 'image_url_john_legend');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (296, 'John Lennon', 'image_url_john_lennon');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (297, 'John Martyn', 'image_url_john_martyn');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (298, 'John Mayer', 'image_url_john_mayer');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (299, 'John Mellencamp', 'image_url_john_mellencamp');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (300, 'John Williams', 'image_url_john_williams');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (301, 'Johnny Cash', 'image_url_johnny_cash');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (302, 'Johnny Hallyday', 'image_url_johnny_hallyday');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (303, 'Johnny Mathis', 'image_url_johnny_mathis');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (304, 'Jonas Brothers', 'image_url_jonas_brothers');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (305, 'Joni Mitchell', 'image_url_joni_mitchell');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (306, 'Jools Holland', 'image_url_jools_holland');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (307, 'Journey', 'image_url_journey');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (308, 'Joy Division', 'image_url_joy_division');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (309, 'Juice WRLD', 'image_url_juice_wrld');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (310, 'Julio Iglesias', 'image_url_julio_iglesias');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (311, 'Justin Bieber', 'image_url_justin_bieber');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (312, 'Justin Timberlake', 'image_url_justin_timberlake');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (313, 'Kaiser Chiefs', 'image_url_kaiser_chiefs');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (314, 'Kanye West', 'image_url_kanye_west');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (315, 'Karen Carpenter', 'image_url_karen_carpenter');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (316, 'Kasabian', 'image_url_kasabian');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (317, 'Kate Bush', 'image_url_kate_bush');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (318, 'Katy Perry', 'image_url_katy_perry');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (319, 'Keith Jarrett', 'image_url_keith_jarrett');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (320, 'Keith Richards', 'image_url_keith_richards');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (321, 'Keith Urban', 'image_url_keith_urban');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (322, 'Kenny G', 'image_url_kenny_g');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (323, 'Kenny Rogers', 'image_url_kenny_rogers');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (324, 'Kenny Wayne Shepherd', 'image_url_kenny_wayne_shepherd');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (325, 'The Killers', 'image_url_the_killers');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (326, 'Kings Of Leon', 'image_url_kings_of_leon');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (327, 'Kiss', 'image_url_kiss');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (328, 'The Kinks', 'image_url_the_kinks');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (329, 'Kool & The Gang', 'image_url_kool_&_the_gang');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (330, 'Kris Kristofferson', 'image_url_kris_kristofferson');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (331, 'Kylie Minogue', 'image_url_kylie_minogue');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (332, 'LL Cool J', 'image_url_ll_cool_j');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (333, 'Lady Gaga', 'image_url_lady_gaga');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (334, 'Lana Del Rey', 'image_url_lana_del_rey');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (335, 'Lauryn Hill', 'image_url_lauryn_hill');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (336, 'LeAnn Rimes', 'image_url_leann_rimes');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (337, 'Led Zeppelin', 'image_url_led_zeppelin');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (338, 'Lee Scratch Perry', 'image_url_lee_scratch_perry');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (339, 'Lenny Kravitz', 'image_url_lenny_kravitz');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (340, 'Leo Sayer', 'image_url_leo_sayer');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (341, 'Leon Bridges', 'image_url_leon_bridges');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (342, 'Leon Russell', 'image_url_leon_russell');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (343, 'Leonard Cohen', 'image_url_leonard_cohen');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (344, 'Les Paul', 'image_url_les_paul');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (345, 'Liam Gallagher', 'image_url_liam_gallagher');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (346, 'Lil Nas X', 'image_url_lil_nas_x');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (347, 'Lil Wayne', 'image_url_lil_wayne');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (348, 'Lil Uzi Vert', 'image_url_lil_uzi_vert');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (349, 'Lil Peep', 'image_url_lil_peep');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (350, 'Linda Ronstadt', 'image_url_linda_ronstadt');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (351, 'Linkin Park', 'image_url_linkin_park');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (352, 'Lionel Richie', 'image_url_lionel_richie');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (353, 'Little Big Town', 'image_url_little_big_town');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (354, 'Little Richard', 'image_url_little_richard');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (355, 'The Living End', 'image_url_the_living_end');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (356, 'Lizzo', 'image_url_lizzo');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (357, 'Lorde', 'image_url_lorde');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (358, 'Los Lobos', 'image_url_los_lobos');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (359, 'Louis Armstrong', 'image_url_louis_armstrong');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (360, 'Louis Jordan', 'image_url_louis_jordan');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (361, 'Luis Miguel', 'image_url_luis_miguel');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (362, 'Luther Vandross', 'image_url_luther_vandross');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (363, 'Lykke Li', 'image_url_lykke_li');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (364, 'M83', 'image_url_m83');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (365, 'MC5', 'image_url_mc5');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (393, 'MGMT', 'image_url_mgmt');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (367, 'Machine Gun Kelly', 'image_url_machine_gun_kelly');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (368, 'Madonna', 'image_url_madonna');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (369, 'Maggie Rogers', 'image_url_maggie_rogers');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (370, 'Mahalia Jackson', 'image_url_mahalia_jackson');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (371, 'Mamas & The Papas', 'image_url_mamas_&_the_papas');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (372, 'The Mamas & The Papas', 'image_url_the_mamas_&_the_papas');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (373, 'Mandy Moore', 'image_url_mandy_moore');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (374, 'Manic Street Preachers', 'image_url_manic_street_preachers');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (375, 'Marc Bolan & T-Rex', 'image_url_marc_bolan_&_t-rex');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (376, 'Mariah Carey', 'image_url_mariah_carey');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (377, 'Marianne Faithfull', 'image_url_marianne_faithfull');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (378, 'Mark Knopfler', 'image_url_mark_knopfler');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (379, 'Mark Ronson', 'image_url_mark_ronson');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (380, 'Maroon 5', 'image_url_maroon_5');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (381, 'Martha & The Vandellas', 'image_url_martha_&_the_vandellas');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (382, 'Martha Reeves & The Vandellas', 'image_url_martha_reeves_&_the_vandellas');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (383, 'Martha Reeves and The Vandellas', 'image_url_martha_reeves_and_the_vandellas');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (384, 'Marvin Gaye', 'image_url_marvin_gaye');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (385, 'Mary J. Blige', 'image_url_mary_j__blige');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (386, 'Massive Attack', 'image_url_massive_attack');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (387, 'Matt Monro', 'image_url_matt_monro');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (388, 'Meat Loaf', 'image_url_meat_loaf');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (389, 'Megadeth', 'image_url_megadeth');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (390, 'Meghan Trainor', 'image_url_meghan_trainor');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (391, 'Mel Torme', 'image_url_mel_torme');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (392, 'Metallica', 'image_url_metallica');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (394, 'Michael Bolton', 'image_url_michael_bolton');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (395, 'Michael Buble', 'image_url_michael_buble');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (396, 'Michael Jackson', 'image_url_michael_jackson');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (397, 'Migos', 'image_url_migos');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (398, 'Mike Oldfield', 'image_url_mike_oldfield');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (399, 'Mike Posner', 'image_url_mike_posner');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (400, 'Miley Cyrus', 'image_url_miley_cyrus');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (401, 'Missy Elliott', 'image_url_missy_elliott');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (402, 'Mitch Miller', 'image_url_mitch_miller');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (403, 'Mitchell', 'image_url_mitchell');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (404, 'The Moody Blues', 'image_url_the_moody_blues');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (405, 'Morrissey', 'image_url_morrissey');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (406, 'Motley Crue', 'image_url_motley_crue');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (407, 'Motorhead', 'image_url_motorhead');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (408, 'Mott The Hoople', 'image_url_mott_the_hoople');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (409, 'Muddy Waters', 'image_url_muddy_waters');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (410, 'Mumford & Sons', 'image_url_mumford_&_sons');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (411, 'Muse', 'image_url_muse');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (412, 'My Chemical Romance', 'image_url_my_chemical_romance');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (413, 'N.W.A', 'image_url_n_w_a');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (414, 'Nancy Sinatra', 'image_url_nancy_sinatra');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (415, 'Natalie Cole', 'image_url_natalie_cole');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (416, 'Natasha Bedingfield', 'image_url_natasha_bedingfield');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (417, 'Nat King Cole', 'image_url_nat_king_cole');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (418, 'Neil Diamond', 'image_url_neil_diamond');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (419, 'Neil Young', 'image_url_neil_young');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (420, 'Nelly', 'image_url_nelly');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (421, 'Nelly Furtado', 'image_url_nelly_furtado');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (422, 'New Kids On The Block', 'image_url_new_kids_on_the_block');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (423, 'New Order', 'image_url_new_order');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (424, 'Nick Cave & The Bad Seeds', 'image_url_nick_cave_&_the_bad_seeds');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (425, 'Nick Drake', 'image_url_nick_drake');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (426, 'Nickelback', 'image_url_nickelback');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (427, 'Nicki Minaj', 'image_url_nicki_minaj');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (428, 'Nina Simone', 'image_url_nina_simone');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (429, 'Nirvana', 'image_url_nirvana');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (430, 'Noah Cyrus', 'image_url_noah_cyrus');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (431, 'Noel Gallagher', 'image_url_noel_gallagher');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (432, 'Norah Jones', 'image_url_norah_jones');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (433, 'The Notorious B.I.G.', 'image_url_the_notorious_b_i_g_');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (434, 'Oasis', 'image_url_oasis');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (435, 'The Offspring', 'image_url_the_offspring');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (436, 'Ol Dirty Bastard', 'image_url_ol__dirty_bastard');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (437, 'Olivia Newton-John', 'image_url_olivia_newton-john');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (438, 'One Direction', 'image_url_one_direction');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (439, 'The Orb', 'image_url_the_orb');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (440, 'Orbital', 'image_url_orbital');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (441, 'Orchestral Manoeuvres In The Dark', 'image_url_orchestral_manoeuvres_in_the_dark');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (442, 'Otis Redding', 'image_url_otis_redding');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (443, 'OutKast', 'image_url_outkast');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (444, 'Ozzy Osbourne', 'image_url_ozzy_osbourne');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (445, 'Panic! At The Disco', 'image_url_panic!_at_the_disco');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (446, 'Papa Roach', 'image_url_papa_roach');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (447, 'Paramore', 'image_url_paramore');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (448, 'Patsy Cline', 'image_url_patsy_cline');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (449, 'Patti Smith', 'image_url_patti_smith');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (450, 'Paul McCartney', 'image_url_paul_mccartney');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (451, 'Paul Simon', 'image_url_paul_simon');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (452, 'Paul Weller', 'image_url_paul_weller');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (453, 'Pearl Jam', 'image_url_pearl_jam');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (454, 'Peggy Lee', 'image_url_peggy_lee');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (455, 'Pendulum', 'image_url_pendulum');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (456, 'Perry Como', 'image_url_perry_como');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (457, 'Pet Shop Boys', 'image_url_pet_shop_boys');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (458, 'Pete Doherty', 'image_url_pete_doherty');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (459, 'Pete Seeger', 'image_url_pete_seeger');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (460, 'Peter Frampton', 'image_url_peter_frampton');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (461, 'Peter Gabriel', 'image_url_peter_gabriel');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (462, 'Peter Green', 'image_url_peter_green');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (463, 'Peter Tosh', 'image_url_peter_tosh');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (464, 'Phil Collins', 'image_url_phil_collins');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (465, 'Phil Spector', 'image_url_phil_spector');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (466, 'Phil Woods', 'image_url_phil_woods');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (467, 'Pink', 'image_url_pink');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (468, 'Pink Floyd', 'image_url_pink_floyd');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (469, 'Pixies', 'image_url_pixies');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (470, 'PJ Harvey', 'image_url_pj_harvey');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (471, 'The Pogues', 'image_url_the_pogues');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (472, 'Portishead', 'image_url_portishead');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (473, 'The Pretenders', 'image_url_the_pretenders');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (474, 'Primal Scream', 'image_url_primal_scream');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (475, 'Prince', 'image_url_prince');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (476, 'Procol Harum', 'image_url_procol_harum');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (477, 'Pulp', 'image_url_pulp');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (478, 'The Pussycat Dolls', 'image_url_the_pussycat_dolls');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (479, 'Queen', 'image_url_queen');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (480, 'Queens Of The Stone Age', 'image_url_queens_of_the_stone_age');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (481, 'Queensrÿche', 'image_url_queensrÿche');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (482, 'Quincy Jones', 'image_url_quincy_jones');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (483, 'Quincy Jones & His Orchestra', 'image_url_quincy_jones_&_his_orchestra');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (484, 'R.E.M.', 'image_url_r_e_m_');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (485, 'R. Kelly', 'image_url_r__kelly');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (486, 'Rage Against The Machine', 'image_url_rage_against_the_machine');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (487, 'The Ramones', 'image_url_the_ramones');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (488, 'Ray Charles', 'image_url_ray_charles');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (489, 'Ray Conniff', 'image_url_ray_conniff');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (490, 'Ray Parker Jr.', 'image_url_ray_parker_jr_');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (491, 'Ray Price', 'image_url_ray_price');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (492, 'Ray Stevens', 'image_url_ray_stevens');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (493, 'Reba McEntire', 'image_url_reba_mcentire');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (494, 'Rebecca Black', 'image_url_rebecca_black');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (495, 'Red Hot Chili Peppers', 'image_url_red_hot_chili_peppers');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (496, 'Redbone', 'image_url_redbone');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (497, 'Regina Spektor', 'image_url_regina_spektor');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (498, 'Rihanna', 'image_url_rihanna');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (499, 'Ritchie Valens', 'image_url_ritchie_valens');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (500, 'Rival Sons', 'image_url_rival_sons');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (501, 'Rob Zombie', 'image_url_rob_zombie');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (502, 'Robbie Williams', 'image_url_robbie_williams');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (503, 'Robert Cray', 'image_url_robert_cray');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (504, 'Robert Johnson', 'image_url_robert_johnson');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (505, 'Rod Stewart', 'image_url_rod_stewart');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (506, 'Roger Miller', 'image_url_roger_miller');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (507, 'Roger Waters', 'image_url_roger_waters');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (508, 'The Rolling Stones', 'image_url_the_rolling_stones');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (509, 'Roxy Music', 'image_url_roxy_music');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (510, 'Roy Orbison', 'image_url_roy_orbison');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (511, 'Run D.M.C.', 'image_url_run-d_m_c_');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (512, 'Rush', 'image_url_rush');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (513, 'Ry Cooder', 'image_url_ry_cooder');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (514, 'Ryan Adams', 'image_url_ryan_adams');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (515, 'S Club 7', 'image_url_s_club_7');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (516, 'Sade', 'image_url_sade');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (517, 'Sam Cooke', 'image_url_sam_cooke');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (518, 'Sam Smith', 'image_url_sam_smith');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (519, 'Santana', 'image_url_santana');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (520, 'Sarah Brightman', 'image_url_sarah_brightman');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (521, 'Sarah McLachlan', 'image_url_sarah_mclachlan');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (522, 'Savage Garden', 'image_url_savage_garden');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (523, 'Scott Walker', 'image_url_scott_walker');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (524, 'Scouting For Girls', 'image_url_scouting_for_girls');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (525, 'Seal', 'image_url_seal');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (526, 'The Shangri-Las', 'image_url_the_shangri-las');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (527, 'Shania Twain', 'image_url_shania_twain');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (528, 'Shawn Mendes', 'image_url_shawn_mendes');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (529, 'Sheryl Crow', 'image_url_sheryl_crow');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (530, 'Sia', 'image_url_sia');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (531, 'Sigur Ros', 'image_url_sigur_ros');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (532, 'Simon & Garfunkel', 'image_url_simon_&_garfunkel');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (533, 'Simple Minds', 'image_url_simple_minds');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (534, 'Simple Plan', 'image_url_simple_plan');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (535, 'Simply Red', 'image_url_simply_red');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (536, 'Sinéad O Connor', 'image_url_sinéad_o_connor');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (537, 'Sister Sledge', 'image_url_sister_sledge');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (538, 'The Sisters Of Mercy', 'image_url_the_sisters_of_mercy');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (539, 'Sixpence None The Richer', 'image_url_sixpence_none_the_richer');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (540, 'Skepta', 'image_url_skepta');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (541, 'Skrillex', 'image_url_skrillex');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (542, 'Slade', 'image_url_slade');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (543, 'Slash', 'image_url_slash');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (544, 'Sleater-Kinney', 'image_url_sleater-kinney');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (545, 'Slipknot', 'image_url_slipknot');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (546, 'Sly & The Family Stone', 'image_url_sly_&_the_family_stone');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (547, 'Small Faces', 'image_url_small_faces');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (548, 'The Smiths', 'image_url_the_smiths');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (549, 'Smokie', 'image_url_smokie');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (550, 'Snoop Dogg', 'image_url_snoop_dogg');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (551, 'Snow Patrol', 'image_url_snow_patrol');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (552, 'Solange', 'image_url_solange');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (553, 'Solomon Burke', 'image_url_solomon_burke');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (554, 'The Specials', 'image_url_the_specials');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (555, 'The Spencer Davis Group', 'image_url_the_spencer_davis_group');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (556, 'Spice Girls', 'image_url_spice_girls');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (557, 'St. Vincent', 'image_url_st__vincent');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (558, 'Staind', 'image_url_staind');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (559, 'Stan Getz', 'image_url_stan_getz');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (560, 'Stan Getz & João Gilberto', 'image_url_stan_getz_&_joão_gilberto');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (561, 'Stan Kenton', 'image_url_stan_kenton');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (562, 'Stanley Clarke', 'image_url_stanley_clarke');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (563, 'Stevie Nicks', 'image_url_stevie_nicks');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (564, 'Stevie Ray Vaughan', 'image_url_stevie_ray_vaughan');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (565, 'Stevie Wonder', 'image_url_stevie_wonder');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (566, 'Sting', 'image_url_sting');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (567, 'The Stone Roses', 'image_url_the_stone_roses');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (568, 'The Stooges', 'image_url_the_stooges');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (569, 'Stormzy', 'image_url_stormzy');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (570, 'The Stranglers', 'image_url_the_stranglers');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (571, 'The Streets', 'image_url_the_streets');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (572, 'Suede', 'image_url_suede');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (573, 'The Supremes', 'image_url_the_supremes');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (574, 'The Supremes & The Temptations', 'image_url_the_supremes_&_the_temptations');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (575, 'The Supremes, The Four Tops', 'image_url_the_supremes__the_four_tops');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (576, 'Supergrass', 'image_url_supergrass');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (577, 'Suzanne Vega', 'image_url_suzanne_vega');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (578, 'The Sweet', 'image_url_the_sweet');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (579, 'System Of A Down', 'image_url_system_of_a_down');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (580, 'T. Rex', 'image_url_t__rex');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (601, 'TLC', 'image_url_tlc');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (582, 'Taj Mahal', 'image_url_taj_mahal');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (583, 'Talking Heads', 'image_url_talking_heads');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (584, 'Tame Impala', 'image_url_tame_impala');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (585, 'Taylor Swift', 'image_url_taylor_swift');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (586, 'Tears For Fears', 'image_url_tears_for_fears');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (587, 'Teddy Pendergrass', 'image_url_teddy_pendergrass');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (588, 'The Temptations', 'image_url_the_temptations');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (589, 'The Temptations & The Supremes', 'image_url_the_temptations_&_the_supremes');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (590, 'The Temptations & Four Tops', 'image_url_the_temptations_&_four_tops');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (591, 'Ten Years After', 'image_url_ten_years_after');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (592, 'The The', 'image_url_the_the');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (593, 'Thelonious Monk', 'image_url_thelonious_monk');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (594, 'Thelonious Monk Quintet', 'image_url_thelonious_monk_quintet');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (595, 'Thin Lizzy', 'image_url_thin_lizzy');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (596, 'Third Eye Blind', 'image_url_third_eye_blind');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (597, 'Thomas Newman', 'image_url_thomas_newman');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (598, 'Three Dog Night', 'image_url_three_dog_night');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (599, 'Tim McGraw', 'image_url_tim_mcgraw');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (600, 'Tina Turner', 'image_url_tina_turner');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (602, 'Tom Petty', 'image_url_tom_petty');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (603, 'Tom Petty And The Heartbreakers', 'image_url_tom_petty_and_the_heartbreakers');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (604, 'Tom Waits', 'image_url_tom_waits');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (605, 'Toni Braxton', 'image_url_toni_braxton');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (606, 'Tool', 'image_url_tool');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (607, 'Tori Amos', 'image_url_tori_amos');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (608, 'The Tornados', 'image_url_the_tornados');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (609, 'Toto', 'image_url_toto');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (610, 'Tracy Chapman', 'image_url_tracy_chapman');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (611, 'Travis', 'image_url_travis');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (612, 'The Triffids', 'image_url_the_triffids');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (613, 'Trisha Yearwood', 'image_url_trisha_yearwood');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (614, 'Troye Sivan', 'image_url_troye_sivan');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (615, 'Twisted Sister', 'image_url_twisted_sister');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (616, 'Tyga', 'image_url_tyga');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (617, 'U2', 'image_url_u2');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (618, 'UB40', 'image_url_ub40');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (619, 'UFO', 'image_url_ufo');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (620, 'Usher', 'image_url_usher');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (621, 'The Vaccines', 'image_url_the_vaccines');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (622, 'Van Halen', 'image_url_van_halen');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (623, 'Van Morrison', 'image_url_van_morrison');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (624, 'Vangelis', 'image_url_vangelis');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (625, 'Vanity Fair', 'image_url_vanity_fair');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (626, 'Various Artists', 'image_url_various_artists');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (627, 'The Velvet Underground', 'image_url_the_velvet_underground');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (628, 'The Verve', 'image_url_the_verve');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (629, 'The Very Best', 'image_url_the_very_best');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (630, 'Vince Guaraldi Trio', 'image_url_vince_guaraldi_trio');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (631, 'Vince Staples', 'image_url_vince_staples');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (632, 'Vince Taylor', 'image_url_vince_taylor');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (633, 'Vinnie Paz', 'image_url_vinnie_paz');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (634, 'Violent Femmes', 'image_url_violent_femmes');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (635, 'Vitamin String Quartet', 'image_url_vitamin_string_quartet');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (636, 'Vivian Green', 'image_url_vivian_green');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (637, 'Wailing Souls', 'image_url_wailing_souls');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (638, 'Waka Flocka Flame', 'image_url_waka_flocka_flame');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (639, 'Wale', 'image_url_wale');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (640, 'Walk The Moon', 'image_url_walk_the_moon');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (641, 'The Walker Brothers', 'image_url_the_walker_brothers');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (642, 'Walter Trout', 'image_url_walter_trout');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (643, 'The Wanted', 'image_url_the_wanted');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (644, 'Warpaint', 'image_url_warpaint');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (645, 'Warren Zevon', 'image_url_warren_zevon');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (646, 'The Waterboys', 'image_url_the_waterboys');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (647, 'We Are Scientists', 'image_url_we_are_scientists');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (648, 'The Weeknd', 'image_url_the_weeknd');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (649, 'The White Stripes', 'image_url_the_white_stripes');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (650, 'The Who', 'image_url_the_who');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (651, 'The Wombats', 'image_url_the_wombats');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (652, 'The xx', 'image_url_the_xx');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (653, 'Wiz Khalifa', 'image_url_wiz_khalifa');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (654, 'Wu-Tang Clan', 'image_url_wu-tang_clan');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (655, 'XTC', 'image_url_xtc');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (656, 'Xzibit', 'image_url_xzibit');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (657, 'Yes', 'image_url_yes');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (658, 'Yo La Tengo', 'image_url_yo_la_tengo');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (659, 'Yoko Ono', 'image_url_yoko_ono');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (660, 'Young Fathers', 'image_url_young_fathers');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (661, 'The Young Rascals', 'image_url_the_young_rascals');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (662, 'Youth Lagoon', 'image_url_youth_lagoon');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (663, 'Yung Lean', 'image_url_yung_lean');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (664, 'Yusuf / Cat Stevens', 'image_url_yusuf_/_cat_stevens');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (665, 'Zac Brown Band', 'image_url_zac_brown_band');
INSERT INTO `artist` (`id`, `name`, `image`) VALUES (666, 'ZZ Top', 'image_url_zz_top');
COMMIT;


-- -----------------------------------------------------
-- Data for table `song`
-- -----------------------------------------------------
START TRANSACTION;
USE `artiststrackerdb`;
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (1, 'Straight From The Heart', '3.3', '1983', 'Rock', 'Cuts Like a Knife', 70);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (2, 'Summer Of 69', '3.35', '1984', 'Rock', 'Reckless', 70);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (3, 'Desire', '3.41', '2002', 'Alternative Rock', 'Demolition', 514);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (4, 'Two', '2.39', '2007', 'Alternative Rock', 'Easy Tiger', 514);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (5, 'New York, New York', '3.46', '2001', 'Alternative Rock', 'Gold', 514);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (6, 'Magick', '2.17', '2008', 'Alternative Rock', 'Cardinology', 514);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (7, 'Rolling in the Deep', '3.48', '2011', 'Pop', '21', 3);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (8, 'Hello', '4.55', '2015', 'Pop', '25', 3);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (9, 'Lovesong', '5.16', '2011', 'Pop', '21', 3);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (10, 'Dream On', '4.28', '1973', 'Hard Rock', 'Aerosmith', 4);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (11, 'Janies Got a Gun', '5.33', '1989', 'Hard Rock', 'Pump', 4);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (12, 'Walk This Way', '3.4', '1975', 'Hard Rock', 'Toys in the Attic', 4);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (13, 'Pink', '3.55', '1997', 'Rock', 'Nine Lives', 4);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (14, 'Dude (Looks Like a Lady)', '4.23', '1987', 'Rock', 'Permanent Vacation', 4);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (15, 'Sweet Emotion', '4.34', '1975', 'Rock', 'Toys in the Attic', 4);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (16, 'The Other Side', '4.06', '1989', 'Rock', 'Pump', 4);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (17, 'Rag Doll', '4.25', '1987', 'Rock', 'Permanent Vacation', 4);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (18, 'What It Takes', '5.11', '1989', 'Rock', 'Pump', 4);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (19, 'Remember (Walking in the Sand)', '4.05', '1979', 'Rock', 'Night in the Ruts', 4);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (20, 'Last Child', '3.27', '1976', 'Rock', 'Rocks', 4);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (21, 'Same Old Song and Dance', '3.53', '1974', 'Rock', 'Get Your Wings', 4);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (22, 'Crazy', '5.17', '1993', 'Rock', 'Get a Grip', 4);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (23, 'Back in the Saddle', '4.4', '1976', 'Rock', 'Rocks', 4);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (24, 'Seasons of Wither', '5.38', '1974', 'Rock', 'Get Your Wings', 4);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (25, 'Livin on the Edge', '6.07', '1993', 'Rock', 'Get a Grip', 4);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (26, 'Cryin', '5.09', '1993', 'Rock', 'Get a Grip', 4);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (27, 'Tear in Your Hand', '4.38', '1992', 'Alternative Rock', 'Little Earthquakes', 607);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (28, 'Cornflake Girl', '5.06', '1994', 'Alternative Rock', 'Under the Pink', 607);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (29, 'Raspberry Swirl', '3.58', '1998', 'Alternative Rock', 'From the Choirgirl Hotel', 607);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (30, 'Marianne', '4.07', '1996', 'Alternative Rock', 'Boys for Pele', 607);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (31, 'Winter', '5.4', '1992', 'Alternative Rock', 'Little Earthquakes', 607);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (32, 'Precious Things', '4.26', '1992', 'Alternative Rock', 'Little Earthquakes', 607);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (33, 'A Sorta Fairytale', '5.28', '2002', 'Alternative Rock', 'Scarlets Walk', 607);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (34, 'Spark', '4.13', '1998', 'Alternative Rock', 'From the Choirgirl Hotel', 607);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (35, 'Horses', '4.46', '1996', 'Alternative Rock', 'Boys for Pele', 607);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (36, 'Silent All These Years', '4.1', '1992', 'Alternative Rock', 'Little Earthquakes', 607);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (37, 'Angels', '4.25', '2003', 'Alternative Rock', 'Tales of a Librarian', 607);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (38, 'Pretty Good Year', '3.25', '1994', 'Alternative Rock', 'Under the Pink', 607);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (39, 'Caught A Lite Sneeze', '4.24', '1996', 'Alternative Rock', 'Boys for Pele', 607);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (40, 'God', '3.58', '1994', 'Alternative Rock', 'Under the Pink', 607);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (41, 'Sleep To Dream', '3.11', '1996', 'Alternative Rock', 'Tidal Wave', 183);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (42, 'Criminal', '5.76', '1996', 'Alternative Rock', 'Tidal Wave', 183);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (43, 'Shadowboxer', '8.0', '1996', 'Alternative Rock', 'Tidal Wave', 183);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (44, 'Never Is A Promise', '2.65', '1996', 'Alternative Rock', 'Tidal Wave', 183);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (45, 'Pale September', '3.01', '1996', 'Alternative Rock', 'Tidal Wave', 183);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (46, 'Carrion', '6.42', '1996', 'Alternative Rock', 'Tidal Wave', 183);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (47, 'I Want You (Live for Decades Rock Live!)', '7.27', '2006', 'Alternative Rock', 'Across the Universe', 183);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (48, 'Across the Universe', '7.24', '1998', 'Alternative Rock', 'I Want You', 183);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (49, 'Paper Bag', '4.54', '1999', 'Alternative Rock', 'Paper Bag', 183);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (50, 'Sullen Girl', '4.77', '1996', 'Alternative Rock', 'Sullen Girl', 183);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (51, 'A Mistake', '6.18', '1999', 'Alternative Rock', 'A Mistake', 183);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (52, 'Get Gone', '6.25', '1999', 'Alternative Rock', 'Get Gone', 183);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (53, 'Get Him Back', '6.5', '2005', 'Alternative Rock', 'Get Him Back', 183);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (54, 'Love Ridden', '6.63', '1999', 'Alternative Rock', 'Love Ridden', 183);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (55, 'Please Please Please', '6.05', '2005', 'Alternative Rock', 'Please Please Please', 183);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (56, 'The Child Is Gone', '6.89', '1996', 'Alternative Rock', 'The Child Is Gone', 183);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (57, 'O Sailor', '7.34', '2005', 'Alternative Rock', 'O Sailor', 183);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (58, 'I Know', '7.84', '1999', 'Alternative Rock', 'I Know', 183);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (59, 'The First Taste', '7.85', '1996', 'Alternative Rock', 'The First Taste', 183);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (60, 'Window', '7.91', '2005', 'Alternative Rock', 'Window', 183);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (61, 'Neighborhood #1 (Tunnels)', '4.01', '2004', 'Indie Rock', 'Funeral', 17);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (62, 'Rebellion (Lies)', '4.29', '2004', 'Indie Rock', 'Funeral', 17);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (63, 'Haiti', '3.31', '2004', 'Indie Rock', 'Funeral', 17);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (64, 'Sprawl II (Mountains Beyond Mountains)', '4.31', '2010', 'Indie Rock', 'The Suburbs', 17);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (65, 'Everything Now', '7.5', '2017', 'Indie Rock', 'Everything Now', 17);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (66, 'Keep the Car Running', '4.38', '2007', 'Indie Rock', 'Neon Bible', 17);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (67, 'We Used to Wait', '3.41', '2010', 'Indie Rock', 'The Suburbs', 17);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (68, 'The Suburbs', '6.29', '2010', 'Indie Rock', 'The Suburbs', 17);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (69, 'Reflektor', '3.39', '2013', 'Indie Rock', 'Reflektor', 17);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (70, 'Neighborhood #2 (Laika)', '5.08', '2004', 'Indie Rock', 'Funeral', 17);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (71, 'No Cars Go', '5.48', '2007', 'Indie Rock', 'Neon Bible', 17);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (72, 'Intervention', '4.86', '2006', 'Indie Rock', 'Neon Bible', 17);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (73, 'Creature Comfort', '6.54', '2017', 'Indie Rock', 'Everything Now', 17);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (74, 'The Well and the Lighthouse', '7.01', '2007', 'Indie Rock', 'Neon Bible', 17);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (75, 'Wake Up', '4.68', '2004', 'Indie Rock', 'Funeral', 17);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (76, 'Ready to Start', '5.09', '2010', 'Indie Rock', 'The Suburbs', 17);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (77, 'Neighborhood #3 (Power Out)', '6.52', '2004', 'Indie Rock', 'Funeral', 17);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (78, 'My Body Is A Cage', '6.46', '2007', 'Indie Rock', 'Neon Bible', 17);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (79, 'Afterlife', '6.8', '2013', 'Indie Rock', 'Reflektor', 17);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (80, 'Abrahams Daughter', '6.92', '2012', 'Indie Rock', 'The Hunger Games: Songs from District 12 and Beyond', 17);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (81, 'Electric Blue', '7.19', '2017', 'Indie Rock', 'Everything Now', 17);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (82, 'Whyd You Only Call Me When Youre High?', '4.93', '2013', 'Indie Rock', 'AM', 18);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (83, 'Dont Sit Down cause Ive Moved Your Chair', '5.71', '2011', 'Indie Rock', 'Suck It and See', 18);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (84, 'Youre So Dark', '5.76', '2013', 'Indie Rock', 'AM', 18);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (85, 'No. 1 Party Anthem', '5.938', '2013', 'Indie Rock', 'AM', 18);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (86, 'Red Light Indicates Doors Are Secure', '5.961', '2006', 'Indie Rock', 'Whatever People Say I Am, Thats What Im Not', 18);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (87, 'Piledriver Waltz', '7.366', '2011', 'Indie Rock', 'Suck It and See', 18);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (88, 'Shes Thunderstorms', '7.438', '2011', 'Indie Rock', 'Suck It and See', 18);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (89, 'Thats Where Youre Wrong', '7.459', '2011', 'Indie Rock', 'Suck It and See', 18);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (90, 'Black Treacle', '7.746', '2011', 'Indie Rock', 'Suck It and See', 18);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (91, 'I Bet You Look Good On The Dancefloor', '7.963', '2005', 'Indie Rock', 'Whatever People Say I Am, Thats What Im Not', 18);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (92, 'So Into You', '6.99', '1977', 'Southern Rock', 'A Rock and Roll Alternative', 23);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (93, 'Champagne Jam', '8.16', '1978', 'Southern Rock', 'Champagne Jam', 23);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (94, 'Spooky', '7.71', '1979', 'Southern Rock', 'Underdog', 23);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (95, 'Doraville', '6.3', '1974', 'Southern Rock', 'Third Annual Pipe Dream', 23);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (96, 'Imaginary Lover', '5.62', '1978', 'Southern Rock', 'Champagne Jam', 23);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (97, 'Doesnt Remind Me', '4.94', '2005', 'Alternative Rock', 'Out of Exile', 24);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (98, 'Be Yourself', '4.212', '2005', 'Alternative Rock', 'Out of Exile', 24);
INSERT INTO `song` (`id`, `name`, `song_length`, `release_year`, `genre`, `album_title`, `artist_id`) VALUES (99, 'Like a Stone', '4.289', '2002', 'Alternative Rock', 'Audioslave', 24);
COMMIT;

